events_list = [
    (0xD825, 2), (0xD825, 3), (0xD825, 4), (0xD825, 5), (0xD826, 5), (0xD826, 6), (0xD827, 2), (0xD827, 3), 
    (0xD828, 1), (0xD829, 2), (0xD829, 3), (0xD829, 4), (0xD82A, 0), (0xD82A, 1), (0xD82B, 2), (0xD82B, 3), 
    (0xD82B, 4), (0xD82B, 5), (0xD82C, 0), (0xD82C, 1), (0xD82C, 2), (0xD82D, 6), (0xD82D, 7), (0xD82E, 0), 
    (0xD82E, 7), (0xD82F, 5), (0xD82F, 6), (0xD82F, 7), (0xD830, 0), (0xD830, 4), (0xD830, 5), (0xD830, 6), 
    (0xD831, 2), (0xD831, 3), (0xD831, 4), (0xD832, 0), (0xD833, 2), (0xD833, 3), (0xD833, 4), (0xD834, 0), 
    (0xD834, 1), (0xD834, 2), (0xD834, 3), (0xD835, 1), (0xD835, 2), (0xD836, 0), (0xD837, 4), (0xD837, 5), 
    (0xD838, 0), (0xD838, 5), (0xD838, 7), (0xD7B9, 7), (0xD7D2, 1), (0xD7D2, 2), (0xD7D2, 3), (0xD7D2, 4), 
    (0xD7D2, 5), (0xD7D2, 6), (0xD7D2, 7), (0xD87D, 1), (0xD87D, 2), (0xD87D, 3), (0xD87D, 4), (0xD87D, 5), 
    (0xD87D, 6), (0xD87D, 7), (0xD87E, 0), (0xD7FF, 4), (0xD803, 1), (0xD803, 2), (0xD803, 3), (0xD803, 4), 
    (0xD803, 5), (0xD805, 1), (0xD805, 2), (0xD805, 3), (0xD805, 4), (0xD807, 1), (0xD807, 2), (0xD807, 3), 
    (0xD807, 4), (0xD809, 1), (0xD809, 2), (0xD809, 3), (0xD809, 4), (0xD809, 5), (0xD809, 6), (0xD7F5, 1), 
    (0xD7F5, 2), (0xD7F5, 3), (0xD7F5, 4), (0xD7F5, 5), (0xD7F5, 6), (0xD7F5, 7), (0xD7F6, 1), (0xD7F6, 2), 
    (0xD7F6, 3), (0xD7F6, 4), (0xD7F6, 5), (0xD7F6, 6), (0xD7F6, 7), (0xD7C3, 2), (0xD7C3, 3), (0xD7C3, 4), 
    (0xD7C3, 5), (0xD7C3, 6), (0xD7C3, 7), (0xD7C4, 0), (0xD7C5, 2), (0xD7EF, 1), (0xD7EF, 2), (0xD7EF, 3), 
    (0xD7EF, 4), (0xD7EF, 5), (0xD7EF, 6), (0xD7EF, 7), (0xD7F1, 1), (0xD7F1, 2), (0xD7F1, 3), (0xD7F1, 4), 
    (0xD7F1, 5), (0xD7F1, 6), (0xD7F1, 7), (0xD7F2, 0), (0xD7F2, 1), (0xD7CF, 1), (0xD7CF, 2), (0xD7CF, 3), 
    (0xD7CF, 4), (0xD7CF, 5), (0xD7CF, 6), (0xD7CF, 7), (0xD7D0, 0), (0xD7D0, 1), (0xD7C9, 1), (0xD7C9, 2), 
    (0xD7C9, 3), (0xD7C9, 4), (0xD7C9, 5), (0xD7C9, 6), (0xD7D5, 1), (0xD7D5, 2), (0xD7D5, 3), (0xD7D5, 4), 
    (0xD7D5, 5), (0xD7D5, 6), (0xD7D5, 7), (0xD7D6, 0), (0xD7D6, 1), (0xD7D6, 2), (0xD7CD, 1), (0xD7CD, 2), 
    (0xD7CD, 3), (0xD7CD, 4), (0xD7CD, 5), (0xD7CD, 6), (0xD7CD, 7), (0xD7CE, 0), (0xD7CE, 1), (0xD7D1, 1), 
    (0xD7D1, 2), (0xD7D1, 3), (0xD7D1, 4), (0xD7D1, 5), (0xD7D1, 6), (0xD7D7, 2), (0xD7D7, 3), (0xD7D7, 4), 
    (0xD7D7, 5), (0xD7D7, 6), (0xD7D7, 7), (0xD7D8, 0), (0xD7DF, 1), (0xD7DF, 2), (0xD7DF, 3), (0xD7DF, 4), 
    (0xD7DF, 5), (0xD7DF, 6), (0xD7E1, 1), (0xD7E1, 2), (0xD7E1, 3), (0xD7E1, 4), (0xD7E1, 5), (0xD7E1, 6), 
    (0xD7E1, 7), (0xD7E2, 0), (0xD7E2, 1), (0xD7E2, 2), (0xD7D9, 1), (0xD7D9, 2), (0xD7D9, 3), (0xD7D9, 4), 
    (0xD7D9, 5), (0xD7D9, 6), (0xD7D9, 7), (0xD7DA, 0), (0xD7DA, 1), (0xD7DA, 2), (0xD7DB, 1), (0xD7DB, 2), 
    (0xD7DB, 3), (0xD7DB, 4), (0xD7DB, 5), (0xD7DB, 6), (0xD7DB, 7), (0xD7DC, 0), (0xD7DC, 1), (0xD7DC, 2), 
    (0xD7DD, 1), (0xD7DD, 2), (0xD7DD, 3), (0xD7DD, 4), (0xD7DD, 5), (0xD7DD, 6), (0xD7DD, 7), (0xD7DE, 0), 
    (0xD7DE, 1), (0xD7DE, 2), (0xD7E3, 1), (0xD7E3, 2), (0xD7E3, 3), (0xD7E5, 1), (0xD7E5, 2), (0xD7E5, 3), 
    (0xD7E5, 4), (0xD7E5, 5), (0xD7E5, 6), (0xD7E5, 7), (0xD7E6, 0), (0xD7E6, 1), (0xD7E6, 2), (0xD7E7, 1), 
    (0xD7E7, 2), (0xD7E7, 3), (0xD7E7, 4), (0xD7E7, 5), (0xD7E7, 6), (0xD7E7, 7), (0xD7E8, 0), (0xD7E8, 1), 
    (0xD7E8, 2), (0xD7E9, 1), (0xD7E9, 2), (0xD7E9, 3), (0xD7E9, 4), (0xD7E9, 5), (0xD7E9, 6), (0xD7E9, 7), 
    (0xD7EA, 0), (0xD7EA, 1), (0xD7C6, 7), (0xD747, 3), (0xD74A, 2), (0xD754, 0), (0xD754, 1), (0xD771, 1), 
    (0xD77E, 2), (0xD77E, 3), (0xD77E, 4), (0xD783, 0), (0xD7BF, 0), (0xD7D6, 7), (0xD7DD, 0), (0xD7E0, 7), 
    (0xD85F, 1), (0xD769, 7), (0xD7D8, 6), (0xD7D8, 7), (0xD7E0, 0), (0xD7E0, 1), (0xD803, 0), (0xD7E0, 6), 
    (0xD857, 0), (0xD78E, 0), (0xD7C2, 0), (0xD755, 6), (0xD75E, 6), (0xD777, 0), (0xD778, 4), (0xD778, 5), 
    (0xD778, 6), (0xD778, 7), (0xD77C, 0), (0xD792, 0), (0xD773, 6), (0xD7BD, 0), (0xD7AF, 0), (0xD7A1, 7), 
    (0xD826, 7), (0xD79A, 0), (0xD751, 0), (0xD74C, 1), (0xD7B3, 0), (0xD7D7, 0), (0xD7F1, 0), (0xD7F2, 3), 
    (0xD7F2, 4), (0xD7F2, 5), (0xD7F2, 6), (0xD7F2, 7), (0xD74B, 7), (0xD747, 0), (0xD74B, 1), (0xD74B, 2), 
    (0xD74B, 0), (0xD74B, 5), (0xD74E, 1), (0xD747, 6), (0xD74E, 0), (0xD74B, 4), (0xD74B, 6), (0xD74A, 0), 
    (0xD74A, 1), (0xD7F3, 2), (0xD7F3, 3), (0xD7F3, 4), (0xD7EF, 0), (0xD7F0, 1), (0xD75B, 7), (0xD75F, 0), 
    (0xD771, 6), (0xD771, 7), (0xD76C, 0), (0xD7A3, 0), (0xD7A3, 1), (0xD7A3, 2), (0xD847, 1), (0xD849, 1), 
    (0xD849, 2), (0xD84B, 1), (0xD84B, 2), (0xD796, 0), (0xD798, 1), (0xD78E, 1), (0xD790, 6), (0xD790, 7), 
    (0xD7B1, 0), (0xD7B1, 1), (0xD7B1, 2), (0xD7B1, 3), (0xD7B1, 4), (0xD7B1, 5), (0xD7B1, 6), (0xD7B1, 7), 
    (0xD815, 1), (0xD815, 2), (0xD815, 3), (0xD815, 4), (0xD815, 5), (0xD817, 1), (0xD819, 1), (0xD819, 2), 
    (0xD81B, 2), (0xD81B, 3), (0xD81B, 4), (0xD81B, 5), (0xD81B, 6), (0xD81B, 7), (0xD77E, 1), (0xD765, 1), 
    (0xD765, 2), (0xD765, 3), (0xD766, 1), (0xD766, 2), (0xD766, 3), (0xD767, 2), (0xD767, 3), (0xD767, 4), 
    (0xD767, 5), (0xD767, 7), (0xD768, 1), (0xD768, 2), (0xD768, 3), (0xD768, 7), (0xD769, 1), (0xD769, 2), 
    (0xD769, 3), (0xD755, 7), (0xD755, 2), (0xD75E, 7), (0xD75E, 2), (0xD75E, 3), (0xD773, 1), (0xD773, 0), 
    (0xD773, 7), (0xD773, 2), (0xD773, 3), (0xD773, 4), (0xD792, 1), (0xD77C, 2), (0xD77C, 3), (0xD77C, 4), 
    (0xD77C, 5), (0xD77C, 6), (0xD77C, 7), (0xD77D, 0), (0xD792, 1), (0xD792, 2), (0xD792, 3), (0xD792, 4), 
    (0xD792, 5), (0xD792, 6), (0xD792, 7), (0xD7B3, 1), (0xD7B3, 2), (0xD7B3, 3), (0xD7B3, 4), (0xD7B3, 5), 
    (0xD7B3, 6), (0xD7B3, 7), (0xD7B4, 0), (0xD79A, 1), (0xD79A, 2), (0xD79A, 3), (0xD79A, 4), (0xD79A, 5), 
    (0xD79A, 6), (0xD79A, 7), (0xD79B, 0), (0xD74C, 0), (0xD751, 1), (0xD751, 2), (0xD751, 3), (0xD751, 4), 
    (0xD751, 5), (0xD751, 6), (0xD751, 7), (0xD752, 0), (0xD752, 1), (0xD74B, 3), (0xD7EB, 0), (0xD7EB, 1), 
    (0xD7EB, 5), (0xD7EB, 6), (0xD75A, 0), (0xD764, 6), (0xD764, 7), (0xD7EB, 7), (0xD82F, 0)
    ]

pokemon_data = [
    {'hex': '1', 'decimal': '1', 'name': 'Rhydon'},
    {'hex': '2', 'decimal': '2', 'name': 'Kangaskhan'},
    {'hex': '3', 'decimal': '3', 'name': 'Nidoran♂'},
    {'hex': '4', 'decimal': '4', 'name': 'Clefairy'},
    {'hex': '5', 'decimal': '5', 'name': 'Spearow'},
    {'hex': '6', 'decimal': '6', 'name': 'Voltorb', 'type': 'Electric'},
    {'hex': '7', 'decimal': '7', 'name': 'Nidoking'},
    {'hex': '8', 'decimal': '8', 'name': 'Slowbro'},
    {'hex': '9', 'decimal': '9', 'name': 'Ivysaur'},
    {'hex': 'A', 'decimal': '10', 'name': 'Exeggutor'},
    {'hex': 'B', 'decimal': '11', 'name': 'Lickitung'},
    {'hex': 'C', 'decimal': '12', 'name': 'Exeggcute'},
    {'hex': 'D', 'decimal': '13', 'name': 'Grimer'},
    {'hex': 'E', 'decimal': '14', 'name': 'Gengar', 'type': 'Ghost'},
    {'hex': 'F', 'decimal': '15', 'name': 'Nidoran♀'},
    {'hex': '10', 'decimal': '16', 'name': 'Nidoqueen'},
    {'hex': '11', 'decimal': '17', 'name': 'Cubone'},
    {'hex': '12', 'decimal': '18', 'name': 'Rhyhorn'},
    {'hex': '13', 'decimal': '19', 'name': 'Lapras', 'type': 'Ice'},
    {'hex': '14', 'decimal': '20', 'name': 'Arcanine'},
    {'hex': '15', 'decimal': '21', 'name': 'Mew'},
    {'hex': '16', 'decimal': '22', 'name': 'Gyarados'},
    {'hex': '17', 'decimal': '23', 'name': 'Shellder'},
    {'hex': '18', 'decimal': '24', 'name': 'Tentacool'},
    {'hex': '19', 'decimal': '25', 'name': 'Gastly', 'type': 'Ghost'},
    {'hex': '1A', 'decimal': '26', 'name': 'Scyther', 'type': 'Bug'},
    {'hex': '1B', 'decimal': '27', 'name': 'Staryu'},
    {'hex': '1C', 'decimal': '28', 'name': 'Blastoise'},
    {'hex': '1D', 'decimal': '29', 'name': 'Pinsir', 'type': 'Bug'},
    {'hex': '1E', 'decimal': '30', 'name': 'Tangela'},
    {'hex': '1F', 'decimal': '31', 'name': 'MissingNo. (Scizor)'},
    {'hex': '20', 'decimal': '32', 'name': 'MissingNo. (Shuckle)'},
    {'hex': '21', 'decimal': '33', 'name': 'Growlithe'},
    {'hex': '22', 'decimal': '34', 'name': 'Onix'},
    {'hex': '23', 'decimal': '35', 'name': 'Fearow'},
    {'hex': '24', 'decimal': '36', 'name': 'Pidgey'},
    {'hex': '25', 'decimal': '37', 'name': 'Slowpoke'},
    {'hex': '26', 'decimal': '38', 'name': 'Kadabra'},
    {'hex': '27', 'decimal': '39', 'name': 'Graveler'},
    {'hex': '28', 'decimal': '40', 'name': 'Chansey'},
    {'hex': '29', 'decimal': '41', 'name': 'Machoke'},
    {'hex': '2A', 'decimal': '42', 'name': 'Mr. Mime'},
    {'hex': '2B', 'decimal': '43', 'name': 'Hitmonlee'},
    {'hex': '2C', 'decimal': '44', 'name': 'Hitmonchan'},
    {'hex': '2D', 'decimal': '45', 'name': 'Arbok'},
    {'hex': '2E', 'decimal': '46', 'name': 'Parasect', 'type': 'Bug'},
    {'hex': '2F', 'decimal': '47', 'name': 'Psyduck'},
    {'hex': '30', 'decimal': '48', 'name': 'Drowzee'},
    {'hex': '31', 'decimal': '49', 'name': 'Golem'},
    {'hex': '32', 'decimal': '50', 'name': 'MissingNo. (Heracross)'},
    {'hex': '33', 'decimal': '51', 'name': 'Magmar'},
    {'hex': '34', 'decimal': '52', 'name': 'MissingNo. (Ho-Oh)'},
    {'hex': '35', 'decimal': '53', 'name': 'Electabuzz', 'type': 'Electric'},
    {'hex': '36', 'decimal': '54', 'name': 'Magneton', 'type': 'Electric'},
    {'hex': '37', 'decimal': '55', 'name': 'Koffing'},
    {'hex': '38', 'decimal': '56', 'name': 'MissingNo. (Sneasel)'},
    {'hex': '39', 'decimal': '57', 'name': 'Mankey'},
    {'hex': '3A', 'decimal': '58', 'name': 'Seel'},
    {'hex': '3B', 'decimal': '59', 'name': 'Diglett'},
    {'hex': '3C', 'decimal': '60', 'name': 'Tauros'},
    {'hex': '3D', 'decimal': '61', 'name': 'MissingNo. (Teddiursa)'},
    {'hex': '3E', 'decimal': '62', 'name': 'MissingNo. (Ursaring)'},
    {'hex': '3F', 'decimal': '63', 'name': 'MissingNo. (Slugma)'},
    {'hex': '40', 'decimal': '64', 'name': 'Farfetch\'d'},
    {'hex': '41', 'decimal': '65', 'name': 'Venonat', 'type': 'Bug'},
    {'hex': '42', 'decimal': '66', 'name': 'Dragonite', 'type': 'Dragon'},
    {'hex': '43', 'decimal': '67', 'name': 'MissingNo. (Magcargo)'},
    {'hex': '44', 'decimal': '68', 'name': 'MissingNo. (Swinub)'},
    {'hex': '45', 'decimal': '69', 'name': 'MissingNo. (Piloswine)'},
    {'hex': '46', 'decimal': '70', 'name': 'Doduo'},
    {'hex': '47', 'decimal': '71', 'name': 'Poliwag'},
    {'hex': '48', 'decimal': '72', 'name': 'Jynx', 'type': 'Ice'},
    {'hex': '49', 'decimal': '73', 'name': 'Moltres'},
    {'hex': '4A', 'decimal': '74', 'name': 'Articuno', 'type': 'Ice'},
    {'hex': '4B', 'decimal': '75', 'name': 'Zapdos', 'type': 'Electric'},
    {'hex': '4C', 'decimal': '76', 'name': 'Ditto'},
    {'hex': '4D', 'decimal': '77', 'name': 'Meowth'},
    {'hex': '4E', 'decimal': '78', 'name': 'Krabby'},
    {'hex': '4F', 'decimal': '79', 'name': 'MissingNo. (Corsola)'},
    {'hex': '50', 'decimal': '80', 'name': 'MissingNo. (Remoraid)'},
    {'hex': '51', 'decimal': '81', 'name': 'MissingNo. (Octillery)'},
    {'hex': '52', 'decimal': '82', 'name': 'Vulpix'},
    {'hex': '53', 'decimal': '83', 'name': 'Ninetales'},
    {'hex': '54', 'decimal': '84', 'name': 'Pikachu', 'type': 'Electric'},
    {'hex': '55', 'decimal': '85', 'name': 'Raichu', 'type': 'Electric'},
    {'hex': '56', 'decimal': '86', 'name': 'MissingNo. (Deli)'},
    {'hex': '57', 'decimal': '87', 'name': 'MissingNo. (Mantine)'},
    {'hex': '58', 'decimal': '88', 'name': 'Dratini', 'type': 'Dragon'},
    {'hex': '59', 'decimal': '89', 'name': 'Dragonair', 'type': 'Dragon'},
    {'hex': '5A', 'decimal': '90', 'name': 'Kabuto'},
    {'hex': '5B', 'decimal': '91', 'name': 'Kabutops'},
    {'hex': '5C', 'decimal': '92', 'name': 'Horsea'},
    {'hex': '5D', 'decimal': '93', 'name': 'Seadra'},
    {'hex': '5E', 'decimal': '94', 'name': 'MissingNo. (Skarmory)'},
    {'hex': '5F', 'decimal': '95', 'name': 'MissingNo. (Houndour)'},
    {'hex': '60', 'decimal': '96', 'name': 'Sandshrew'},
    {'hex': '61', 'decimal': '97', 'name': 'Sandslash'},
    {'hex': '62', 'decimal': '98', 'name': 'Omanyte'},
    {'hex': '63', 'decimal': '99', 'name': 'Omastar'},
    {'hex': '64', 'decimal': '100', 'name': 'Jigglypuff'},
    {'hex': '65', 'decimal': '101', 'name': 'Wigglytuff'},
    {'hex': '66', 'decimal': '102', 'name': 'Eevee'},
    {'hex': '67', 'decimal': '103', 'name': 'Flareon'},
    {'hex': '68', 'decimal': '104', 'name': 'Jolteon', 'type': 'Electric'},
    {'hex': '69', 'decimal': '105', 'name': 'Vaporeon'},
    {'hex': '6A', 'decimal': '106', 'name': 'Machop'},
    {'hex': '6B', 'decimal': '107', 'name': 'Zubat'},
    {'hex': '6C', 'decimal': '108', 'name': 'Ekans'},
    {'hex': '6D', 'decimal': '109', 'name': 'Paras', 'type': 'Bug'},
    {'hex': '6E', 'decimal': '110', 'name': 'Poliwhirl'},
    {'hex': '6F', 'decimal': '111', 'name': 'Poliwrath'},
    {'hex': '70', 'decimal': '112', 'name': 'Weedle', 'type': 'Bug'},
    {'hex': '71', 'decimal': '113', 'name': 'Kakuna', 'type': 'Bug'},
    {'hex': '72', 'decimal': '114', 'name': 'Beedrill', 'type': 'Bug'},
    {'hex': '73', 'decimal': '115', 'name': 'MissingNo. (Houndoom)'},
    {'hex': '74', 'decimal': '116', 'name': 'Dodrio'},
    {'hex': '75', 'decimal': '117', 'name': 'Primeape'},
    {'hex': '76', 'decimal': '118', 'name': 'Dugtrio'},
    {'hex': '77', 'decimal': '119', 'name': 'Venomoth', 'type': 'Bug'},
    {'hex': '78', 'decimal': '120', 'name': 'Dewgong', 'type': 'Ice'},
    {'hex': '79', 'decimal': '121', 'name': 'MissingNo. (Kingdra)'},
    {'hex': '7A', 'decimal': '122', 'name': 'MissingNo. (Phanpy)'},
    {'hex': '7B', 'decimal': '123', 'name': 'Caterpie', 'type': 'Bug'},
    {'hex': '7C', 'decimal': '124', 'name': 'Metapod', 'type': 'Bug'},
    {'hex': '7D', 'decimal': '125', 'name': 'Butterfree', 'type': 'Bug'},
    {'hex': '7E', 'decimal': '126', 'name': 'Machamp'},
    {'hex': '7F', 'decimal': '127', 'name': 'MissingNo. (Donphan)'},
    {'hex': '80', 'decimal': '128', 'name': 'Golduck'},
    {'hex': '81', 'decimal': '129', 'name': 'Hypno'},
    {'hex': '82', 'decimal': '130', 'name': 'Golbat'},
    {'hex': '83', 'decimal': '131', 'name': 'Mewtwo'},
    {'hex': '84', 'decimal': '132', 'name': 'Snorlax'},
    {'hex': '85', 'decimal': '133', 'name': 'Magikarp'},
    {'hex': '86', 'decimal': '134', 'name': 'MissingNo. (Porygon2)'},
    {'hex': '87', 'decimal': '135', 'name': 'MissingNo. (Stantler)'},
    {'hex': '88', 'decimal': '136', 'name': 'Muk'},
    {'hex': '89', 'decimal': '137', 'name': 'MissingNo. (Smeargle)'},
    {'hex': '8A', 'decimal': '138', 'name': 'Kingler'},
    {'hex': '8B', 'decimal': '139', 'name': 'Cloyster'},
    {'hex': '8D', 'decimal': '141', 'name': 'Electrode'},
    {'hex': '8E', 'decimal': '142', 'name': 'Clefable'},
    {'hex': '8F', 'decimal': '143', 'name': 'Weezing'},
    {'hex': '90', 'decimal': '144', 'name': 'Persian'},
    {'hex': '91', 'decimal': '145', 'name': 'Marowak'},
    {'hex': '93', 'decimal': '147', 'name': 'Haunter'},
    {'hex': '94', 'decimal': '148', 'name': 'Abra'},
    {'hex': '95', 'decimal': '149', 'name': 'Alakazam'},
    {'hex': '96', 'decimal': '150', 'name': 'Pidgeotto'},
    {'hex': '97', 'decimal': '151', 'name': 'Pidgeot'},
    {'hex': '98', 'decimal': '152', 'name': 'Starmie'},
    {'hex': '99', 'decimal': '153', 'name': 'Bulbasaur'},
    {'hex': '9A', 'decimal': '154', 'name': 'Venusaur'},
    {'hex': '9B', 'decimal': '155', 'name': 'Tentacruel'},
    {'hex': '9D', 'decimal': '157', 'name': 'Goldeen'},
    {'hex': '9E', 'decimal': '158', 'name': 'Seaking'},
    {'hex': 'A3', 'decimal': '163', 'name': 'Ponyta'},
    {'hex': 'A4', 'decimal': '164', 'name': 'Rapidash'},
    {'hex': 'A5', 'decimal': '165', 'name': 'Rattata'},
    {'hex': 'A6', 'decimal': '166', 'name': 'Raticate'},
    {'hex': 'A7', 'decimal': '167', 'name': 'Nidorino'},
    {'hex': 'A8', 'decimal': '168', 'name': 'Nidorina'},
    {'hex': 'A9', 'decimal': '169', 'name': 'Geodude'},
    {'hex': 'AA', 'decimal': '170', 'name': 'Porygon'},
    {'hex': 'AB', 'decimal': '171', 'name': 'Aerodactyl'},
    {'hex': 'AD', 'decimal': '173', 'name': 'Magnemite'},
    {'hex': 'B0', 'decimal': '176', 'name': 'Charmander'},
    {'hex': 'B1', 'decimal': '177', 'name': 'Squirtle'},
    {'hex': 'B2', 'decimal': '178', 'name': 'Charmeleon'},
    {'hex': 'B3', 'decimal': '179', 'name': 'Wartortle'},
    {'hex': 'B4', 'decimal': '180', 'name': 'Charizard'},
    {'hex': 'B9', 'decimal': '185', 'name': 'Oddish'},
    {'hex': 'BA', 'decimal': '186', 'name': 'Gloom'},
    {'hex': 'BB', 'decimal': '187', 'name': 'Vileplume'},
    {'hex': 'BC', 'decimal': '188', 'name': 'Bellsprout'},
    {'hex': 'BD', 'decimal': '189', 'name': 'Weepinbell'},
    {'hex': 'BE', 'decimal': '190', 'name': 'Victreebel'}
]

moves_dict = {
    1: {"Move": "Pound", "Type": "Normal", "Phy/Spec": "Physical", "PP": 35, "Power": 40, "Acc": "100%"},
    2: {"Move": "Karate Chop", "Type": "Fighting", "Phy/Spec": "Physical", "PP": 25, "Power": 50, "Acc": "100%"},
    3: {"Move": "Double Slap", "Type": "Normal", "Phy/Spec": "Physical", "PP": 10, "Power": 15, "Acc": "85%"},
    4: {"Move": "Comet Punch", "Type": "Normal", "Phy/Spec": "Physical", "PP": 15, "Power": 18, "Acc": "85%"},
    5: {"Move": "Mega Punch", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 80, "Acc": "85%"},
    6: {"Move": "Pay Day", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 40, "Acc": "100%"},
    7: {"Move": "Fire Punch", "Type": "Fire", "Phy/Spec": "Physical", "PP": 15, "Power": 75, "Acc": "100%"},
    8: {"Move": "Ice Punch", "Type": "Ice", "Phy/Spec": "Physical", "PP": 15, "Power": 75, "Acc": "100%"},
    9: {"Move": "Thunder Punch", "Type": "Electric", "Phy/Spec": "Physical", "PP": 15, "Power": 75, "Acc": "100%"},
    10: {"Move": "Scratch", "Type": "Normal", "Phy/Spec": "Physical", "PP": 35, "Power": 40, "Acc": "100%"},
    11: {"Move": "Vise Grip", "Type": "Normal", "Phy/Spec": "Physical", "PP": 30, "Power": 55, "Acc": "100%"},
    12: {"Move": "Guillotine", "Type": "Normal", "Phy/Spec": "Physical", "PP": 5, "Power": "—", "Acc": "30%"},
    13: {"Move": "Razor Wind", "Type": "Normal", "Phy/Spec": "Special", "PP": 10, "Power": 80, "Acc": "100%"},
    14: {"Move": "Swords Dance", "Type": "Normal", "Phy/Spec": "Status", "PP": 20, "Power": "—", "Acc": "—%"},
    15: {"Move": "Cut", "Type": "Normal", "Phy/Spec": "Physical", "PP": 30, "Power": 50, "Acc": "95%"},
    16: {"Move": "Gust", "Type": "Flying", "Phy/Spec": "Special", "PP": 35, "Power": 40, "Acc": "100%"},
    17: {"Move": "Wing Attack", "Type": "Flying", "Phy/Spec": "Physical", "PP": 35, "Power": 60, "Acc": "100%"},
    18: {"Move": "Whirlwind", "Type": "Normal", "Phy/Spec": "Status", "PP": 20, "Power": "—", "Acc": "—%"},
    19: {"Move": "Fly", "Type": "Flying", "Phy/Spec": "Physical", "PP": 15, "Power": 90, "Acc": "95%"},
    20: {"Move": "Bind", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 15, "Acc": "85%"},
    21: {"Move": "Slam", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 80, "Acc": "75%"},
    22: {"Move": "Vine Whip", "Type": "Grass", "Phy/Spec": "Physical", "PP": 25, "Power": 45, "Acc": "100%"},
    23: {"Move": "Stomp", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 65, "Acc": "100%"},
    24: {"Move": "Double Kick", "Type": "Fighting", "Phy/Spec": "Physical", "PP": 30, "Power": 30, "Acc": "100%"},
    25: {"Move": "Mega Kick", "Type": "Normal", "Phy/Spec": "Physical", "PP": 5, "Power": 120, "Acc": "75%"},
    26: {"Move": "Jump Kick", "Type": "Fighting", "Phy/Spec": "Physical", "PP": 10, "Power": 100, "Acc": "95%"},
    27: {"Move": "Rolling Kick", "Type": "Fighting", "Phy/Spec": "Physical", "PP": 15, "Power": 60, "Acc": "85%"},
    28: {"Move": "Sand Attack", "Type": "Ground", "Phy/Spec": "Status", "PP": 15, "Power": "—", "Acc": "100%"},
    29: {"Move": "Headbutt", "Type": "Normal", "Phy/Spec": "Physical", "PP": 15, "Power": 70, "Acc": "100%"},
    30: {"Move": "Horn Attack", "Type": "Normal", "Phy/Spec": "Physical", "PP": 25, "Power": 65, "Acc": "100%"},
    31: {"Move": "Fury Attack", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 15, "Acc": "85%"},
    32: {"Move": "Horn Drill", "Type": "Normal", "Phy/Spec": "Physical", "PP": 5, "Power": "—", "Acc": "30%"},
    33: {"Move": "Tackle", "Type": "Normal", "Phy/Spec": "Physical", "PP": 35, "Power": 40, "Acc": "100%"},
    34: {"Move": "Body Slam", "Type": "Normal", "Phy/Spec": "Physical", "PP": 15, "Power": 85, "Acc": "100%"},
    35: {"Move": "Wrap", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 15, "Acc": "90%"},
    36: {"Move": "Take Down", "Type": "Normal", "Phy/Spec": "Physical", "PP": 20, "Power": 90, "Acc": "85%"},
    37: {"Move": "Thrash", "Type": "Normal", "Phy/Spec": "Physical", "PP": 10, "Power": 120, "Acc": "100%"},
    38: {"Move": "Double-Edge", "Type": "Normal", "Phy/Spec": "Physical", "PP": 15, "Power": 120, "Acc": "100%"},
    39: {"Move": "Tail Whip", "Type": "Normal", "Phy/Spec": "Status", "PP": 30, "Power": "—", "Acc": "100%"},
    40: {"Move": "Poison Sting", "Type": "Poison", "Phy/Spec": "Physical", "PP": 35, "Power": 15, "Acc": "100%"},
    41: {"Move": "Twineedle", "Type": "Bug", "Phy/Spec": "Physical", "PP": 20, "Power": 25, "Acc": "100%"},
    42: {"Move": "Pin Missile", "Type": "Bug", "Phy/Spec": "Physical", "PP": 20, "Power": 25, "Acc": "95%"},
    43: {"Move": "Leer", "Type": "Normal", "Phy/Spec": "Status", "PP": 30, "Power": "—", "Acc": "100%"},
    44: {"Move": "Bite", "Type": "Dark", "Phy/Spec": "Physical", "PP": 25, "Power": 60, "Acc": "100%"},
    45: {"Move": "Growl", "Type": "Normal", "Phy/Spec": "Status", "PP": 40, "Power": "—", "Acc": "100%"},
    46: {"Move": "Roar", "Type": "Normal", "Phy/Spec": "Status", "PP": 20, "Power": "—", "Acc": "—%"},
    47: {"Move": "Sing", "Type": "Normal", "Phy/Spec": "Status", "PP": 15, "Power": "—", "Acc": "55%"},
    48: {"Move": "Supersonic", "Type": "Normal", "Phy/Spec": "Status", "PP": 20, "Power": "—", "Acc": "55%"},
    49: {"Move": "Sonic Boom", "Type": "Normal", "Phy/Spec": "Special", "PP": 20, "Power": "—", "Acc": "90%"},
    50: {"Move": "Disable", "Type": "Normal", "Phy/Spec": "Status", "PP": 20, "Power": "—", "Acc": "100%"},
    51: {"Move": "Acid", "Type": "Poison", "Phy/Spec": "Special", "PP": 30, "Power": 40, "Acc": "100%"},
    52: {"Move": "Ember", "Type": "Fire", "Phy/Spec": "Special", "PP": 25, "Power": 40, "Acc": "100%"},
    53: {"Move": "Flamethrower", "Type": "Fire", "Phy/Spec": "Special", "PP": 15, "Power": 90, "Acc": "100%"},
    54: {"Move": "Mist", "Type": "Ice", "Phy/Spec": "Status", "PP": 30, "Power": "—", "Acc": "—%"},
    55: {"Move": "Water Gun", "Type": "Water", "Phy/Spec": "Special", "PP": 25, "Power": 40, "Acc": "100%"},
    56: {"Move": "Hydro Pump", "Type": "Water", "Phy/Spec": "Special", "PP": 5, "Power": 110, "Acc": "80%"},
    57: {"Move": "Surf", "Type": "Water", "Phy/Spec": "Special", "PP": 15, "Power": 90, "Acc": "100%"},
    58: {"Move": "Ice Beam", "Type": "Ice", "Phy/Spec": "Special", "PP": 10, "Power": 90, "Acc": "100%"},
    59: {"Move": "Blizzard", "Type": "Ice", "Phy/Spec": "Special", "PP": 5, "Power": 110, "Acc": "70%"},
    60: {"Move": "Psybeam", "Type": "Psychic", "Phy/Spec": "Special", "PP": 20, "Power": 65, "Acc": "100%"},
    61: {"Move": "Bubble Beam", "Type": "Water", "Phy/Spec": "Special", "PP": 20, "Power": 65, "Acc": "100%"},
    62: {"Move": "Aurora Beam", "Type": "Ice", "Phy/Spec": "Special", "PP": 20, "Power": 65, "Acc": "100%"},
    63: {"Move": "Hyper Beam", "Type": "Normal", "Phy/Spec": "Special", "PP": 5, "Power": 150, "Acc": "90%"},
    64: {"Move": "Peck", "Type": "Flying", "Phy/Spec": "Physical", "PP": 35, "Power": 35, "Acc": "100%"},
    65: {"Move": "Drill Peck", "Type": "Flying", "Phy/Spec": "Physical", "PP": 20, "Power": 80, "Acc": "100%"},
    66: {"Move": "Submission", "Type": "Fighting", "Phy/Spec": "Physical", "PP": 20, "Power": 80, "Acc": "80%"},
    67: {"Move": "Low Kick", "Type": "Fighting", "Phy/Spec": "Physical", "PP": 20, "Power": "—", "Acc": "100%"},
    68: {"Move": 'Counter', 'Type': 'Fighting', 'Category': 'Physical', 'PP': 20, 'Power': '—', 'Accuracy': '100%'},
    69: {"Move": 'Seismic Toss', 'Type': 'Fighting', 'Category': 'Physical', 'PP': 20, 'Power': '—', 'Accuracy': '100%'},
    70: {"Move": 'Strength', 'Type': 'Normal', 'Category': 'Physical', 'PP': 15, 'Power': 80, 'Accuracy': '100%'},
    71: {"Move": 'Absorb', 'Type': 'Grass', 'Category': 'Special', 'PP': 25, 'Power': 20, 'Accuracy': '100%'},
    72: {"Move": 'Mega Drain', 'Type': 'Grass', 'Category': 'Special', 'PP': 15, 'Power': 40, 'Accuracy': '100%'},
    73: {"Move": 'Leech Seed', 'Type': 'Grass', 'Category': 'Status', 'PP': 10, 'Power': '—', 'Accuracy': '90%'},
    74: {"Move": 'Growth', 'Type': 'Normal', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '—%'},
    75: {"Move": 'Razor Leaf', 'Type': 'Grass', 'Category': 'Physical', 'PP': 25, 'Power': 55, 'Accuracy': '95%'},
    76: {"Move": 'Solar Beam', 'Type': 'Grass', 'Category': 'Special', 'PP': 10, 'Power': 120, 'Accuracy': '100%'},
    77: {"Move": 'Poison Powder', 'Type': 'Poison', 'Category': 'Status', 'PP': 35, 'Power': '—', 'Accuracy': '75%'},
    78: {"Move": 'Stun Spore', 'Type': 'Grass', 'Category': 'Status', 'PP': 30, 'Power': '—', 'Accuracy': '75%'},
    79: {"Move": 'Sleep Powder', 'Type': 'Grass', 'Category': 'Status', 'PP': 15, 'Power': '—', 'Accuracy': '75%'},
    80: {"Move": 'Petal Dance', 'Type': 'Grass', 'Category': 'Special', 'PP': 10, 'Power': 120, 'Accuracy': '100%'},
    81: {"Move": 'String Shot', 'Type': 'Bug', 'Category': 'Status', 'PP': 40, 'Power': '—', 'Accuracy': '95%'},
    82: {"Move": 'Dragon Rage', 'Type': 'Dragon', 'Category': 'Special', 'PP': 10, 'Power': '—', 'Accuracy': '100%'},
    83: {"Move": 'Fire Spin', 'Type': 'Fire', 'Category': 'Special', 'PP': 15, 'Power': 35, 'Accuracy': '85%'},
    84: {"Move": 'Thunder Shock', 'Type': 'Electric', 'Category': 'Special', 'PP': 30, 'Power': 40, 'Accuracy': '100%'},
    85: {"Move": 'Thunderbolt', 'Type': 'Electric', 'Category': 'Special', 'PP': 15, 'Power': 90, 'Accuracy': '100%'},
    86: {"Move": 'Thunder Wave', 'Type': 'Electric', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '90%'},
    87: {"Move": 'Thunder', 'Type': 'Electric', 'Category': 'Special', 'PP': 10, 'Power': 110, 'Accuracy': '70%'},
    88: {"Move": 'Rock Throw', 'Type': 'Rock', 'Category': 'Physical', 'PP': 15, 'Power': 50, 'Accuracy': '90%'},
    89: {"Move": 'Earthquake', 'Type': 'Ground', 'Category': 'Physical', 'PP': 10, 'Power': 100, 'Accuracy': '100%'},
    90: {"Move": 'Fissure', 'Type': 'Ground', 'Category': 'Physical', 'PP': 5, 'Power': '—', 'Accuracy': '30%'},
    91: {"Move": 'Dig', 'Type': 'Ground', 'Category': 'Physical', 'PP': 10, 'Power': 80, 'Accuracy': '100%'},
    92: {"Move": 'Toxic', 'Type': 'Poison', 'Category': 'Status', 'PP': 10, 'Power': '—', 'Accuracy': '90%'},
    93: {"Move": 'Confusion', 'Type': 'Psychic', 'Category': 'Special', 'PP': 25, 'Power': 50, 'Accuracy': '100%'},
    94: {"Move": 'Psychic', 'Type': 'Psychic', 'Category': 'Special', 'PP': 10, 'Power': 90, 'Accuracy': '100%'},
    95: {"Move": 'Hypnosis', 'Type': 'Psychic', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '60%'},
    96: {"Move": 'Meditate', 'Type': 'Psychic', 'Category': 'Status', 'PP': 40, 'Power': '—', 'Accuracy': '—%'},
    97: {"Move": 'Agility', 'Type': 'Psychic', 'Category': 'Status', 'PP': 30, 'Power': '—', 'Accuracy': '—%'},
    98: {"Move": 'Quick Attack', 'Type': 'Normal', 'Category': 'Physical', 'PP': 30, 'Power': 40, 'Accuracy': '100%'},
    99: {"Move": 'Rage', 'Type': 'Normal', 'Category': 'Physical', 'PP': 20, 'Power': 20, 'Accuracy': '100%'},
    100: {"Move": 'Teleport', 'Type': 'Psychic', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '—%'},
    101: {"Move": 'Night Shade', 'Type': 'Ghost', 'Category': 'Special', 'PP': 15, 'Power': '—', 'Accuracy': '100%'},
    102: {"Move": 'Mimic', 'Type': 'Normal', 'Category': 'Status', 'PP': 10, 'Power': '—', 'Accuracy': '—%'},
    103: {"Move": 'Screech', 'Type': 'Normal', 'Category': 'Status', 'PP': 40, 'Power': '—', 'Accuracy': '85%'},
    104: {"Move": 'Double Team', 'Type': 'Normal', 'Category': 'Status', 'PP': 15, 'Power': '—', 'Accuracy': '—%'},
    105: {"Move": 'Recover', 'Type': 'Normal', 'Category': 'Status', 'PP': 5, 'Power': '—', 'Accuracy': '—%'},
    106: {"Move": 'Harden', 'Type': 'Normal', 'Category': 'Status', 'PP': 30, 'Power': '—', 'Accuracy': '—%'},
    107: {"Move": 'Minimize', 'Type': 'Normal', 'Category': 'Status', 'PP': 10, 'Power': '—', 'Accuracy': '—%'},
    108: {"Move": 'Smokescreen', 'Type': 'Normal', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '100%'},
    109: {"Move": 'Confuse Ray', 'Type': 'Ghost', 'Category': 'Status', 'PP': 10, 'Power': '—', 'Accuracy': '100%'},
    110: {"Move": 'Withdraw', 'Type': 'Water', 'Category': 'Status', 'PP': 40, 'Power': '—', 'Accuracy': '—%'},
    111: {"Move": 'Defense Curl', 'Type': 'Normal', 'Category': 'Status', 'PP': 40, 'Power': '—', 'Accuracy': '—%'},
    112: {"Move": 'Barrier', 'Type': 'Psychic', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '—%'},
    113: {"Move": 'Light Screen', 'Type': 'Psychic', 'Category': 'Status', 'PP': 30, 'Power': '—', 'Accuracy': '—%'},
    114: {"Move": 'Haze', 'Type': 'Ice', 'Category': 'Status', 'PP': 30, 'Power': '—', 'Accuracy': '—%'},
    115: {"Move": 'Reflect', 'Type': 'Psychic', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '—%'},
    116: {"Move": 'Focus Energy', 'Type': 'Normal', 'Category': 'Status', 'PP': 30, 'Power': '—', 'Accuracy': '—%'},
    117: {"Move": 'Bide', 'Type': 'Normal', 'Category': 'Physical', 'PP': 10, 'Power': '—', 'Accuracy': '—%'},
    118: {"Move": 'Metronome', 'Type': 'Normal', 'Category': 'Status', 'PP': 10, 'Power': '—', 'Accuracy': '—%'},
    119: {"Move": 'Mirror Move', 'Type': 'Flying', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '—%'},
    120: {"Move": 'Self-Destruct', 'Type': 'Normal', 'Category': 'Physical', 'PP': 5, 'Power': 200, 'Accuracy': '100%'},
    121: {"Move": 'Egg Bomb', 'Type': 'Normal', 'Category': 'Physical', 'PP': 10, 'Power': 100, 'Accuracy': '75%'},
    122: {"Move": 'Lick', 'Type': 'Ghost', 'Category': 'Physical', 'PP': 30, 'Power': 30, 'Accuracy': '100%'},
    123: {"Move": 'Smog', 'Type': 'Poison', 'Category': 'Special', 'PP': 20, 'Power': 30, 'Accuracy': '70%'},
    124: {"Move": 'Sludge', 'Type': 'Poison', 'Category': 'Special', 'PP': 20, 'Power': 65, 'Accuracy': '100%'},
    125: {"Move": 'Bone Club', 'Type': 'Ground', 'Category': 'Physical', 'PP': 20, 'Power': 65, 'Accuracy': '85%'},
    126: {"Move": 'Fire Blast', 'Type': 'Fire', 'Category': 'Special', 'PP': 5, 'Power': 110, 'Accuracy': '85%'},
    127: {"Move": 'Waterfall', 'Type': 'Water', 'Category': 'Physical', 'PP': 15, 'Power': 80, 'Accuracy': '100%'},
    128: {"Move": 'Clamp', 'Type': 'Water', 'Category': 'Physical', 'PP': 15, 'Power': 35, 'Accuracy': '85%'},
    129: {"Move": 'Swift', 'Type': 'Normal', 'Category': 'Special', 'PP': 20, 'Power': 60, 'Accuracy': '—%'},
    130: {"Move": 'Skull Bash', 'Type': 'Normal', 'Category': 'Physical', 'PP': 10, 'Power': 130, 'Accuracy': '100%'},
    131: {"Move": 'Spike Cannon', 'Type': 'Normal', 'Category': 'Physical', 'PP': 15, 'Power': 20, 'Accuracy': '100%'},
    132: {"Move": 'Constrict', 'Type': 'Normal', 'Category': 'Physical', 'PP': 35, 'Power': 10, 'Accuracy': '100%'},
    133: {"Move": 'Amnesia', 'Type': 'Psychic', 'Category': 'Status', 'PP': 20, 'Power': '—', 'Accuracy': '—%'},
    134: {"Move": 'Kinesis', 'Type': 'Psychic', 'Category': 'Status', 'PP': 15, 'Power': '—', 'Accuracy': '80%'},
    135: {"Move": 'Soft-Boiled', 'Type': 'Normal', 'Category': 'Status', 'PP': 5, 'Power': '—', 'Accuracy': '—%'},
    136: {"Move": 'High Jump Kick', 'Type': 'Fighting', 'Category': 'Physical', 'PP': 10, 'Power': 130, 'Accuracy': '90%'},
    137: {"Move": 'Glare', 'Type': 'Normal', 'Category': 'Status', 'PP': 30, 'Power': '—', 'Accuracy': '100%'},
    138: {"Move": 'Dream Eater', 'Type': 'Psychic', 'Category': 'Special', 'PP': 15, 'Power': 100, 'Accuracy': '100%'},
    139: {"Move": 'Poison Gas', 'Type': 'Poison', 'Category': 'Status', 'Power': 40, 'Accuracy': 90},
    140: {"Move": 'Barrage', 'Type': 'Normal', 'Category': 'Physical', 'Power': 20, 'PP': 15, 'Accuracy': 85},
    141: {"Move": 'Leech Life', 'Type': 'Bug', 'Category': 'Physical', 'Power': 10, 'PP': 80, 'Accuracy': 100},
    142: {"Move": 'Lovely Kiss', 'Type': 'Normal', 'Category': 'Status', 'Power': 10, 'Accuracy': 75},
    143: {"Move": 'Sky Attack', 'Type': 'Flying', 'Category': 'Physical', 'Power': 5, 'PP': 140, 'Accuracy': 90},
    144: {"Move": 'Transform', 'Type': 'Normal', 'Category': 'Status', 'Power': 10},
    145: {"Move": 'Bubble', 'Type': 'Water', 'Category': 'Special', 'Power': 30, 'PP': 40, 'Accuracy': 100},
    146: {"Move": 'Dizzy Punch', 'Type': 'Normal', 'Category': 'Physical', 'Power': 10, 'PP': 70, 'Accuracy': 100},
    147: {"Move": 'Spore', 'Type': 'Grass', 'Category': 'Status', 'Power': 15, 'Accuracy': 100},
    148: {"Move": 'Flash', 'Type': 'Normal', 'Category': 'Status', 'Power': 20, 'Accuracy': 100},
    149: {"Move": 'Psywave', 'Type': 'Psychic', 'Category': 'Special', 'Power': 15, 'Accuracy': 100},
    150: {"Move": 'Splash', 'Type': 'Normal', 'Category': 'Status', 'Power': 40},
    151: {"Move": 'Acid Armor', 'Type': 'Poison', 'Category': 'Status', 'Power': 20},
    152: {"Move": 'Crabhammer', 'Type': 'Water', 'Category': 'Physical', 'Power': 10, 'PP': 100, 'Accuracy': 90},
    153: {"Move": 'Explosion', 'Type': 'Normal', 'Category': 'Physical', 'Power': 5, 'PP': 250, 'Accuracy': 100},
    154: {"Move": 'Fury Swipes', 'Type': 'Normal', 'Category': 'Physical', 'Power': 15, 'PP': 18, 'Accuracy': 80},
    155: {"Move": 'Bonemerang', 'Type': 'Ground', 'Category': 'Physical', 'Power': 10, 'PP': 50, 'Accuracy': 90},
    156: {"Move": 'Rest', 'Type': 'Psychic', 'Category': 'Status', 'Power': 5},
    157: {"Move": 'Rock Slide', 'Type': 'Rock', 'Category': 'Physical', 'Power': 10, 'PP': 75, 'Accuracy': 90},
    158: {"Move": 'Hyper Fang', 'Type': 'Normal', 'Category': 'Physical', 'Power': 15, 'PP': 80, 'Accuracy': 90},
    159: {"Move": 'Sharpen', 'Type': 'Normal', 'Category': 'Status', 'Power': 30},
    160: {"Move": 'Conversion', 'Type': 'Normal', 'Category': 'Status', 'Power': 30},
    161: {"Move": 'Tri Attack', 'Type': 'Normal', 'Category': 'Special', 'Power': 10, 'PP': 80, 'Accuracy': 100},
    162: {"Move": 'Super Fang', 'Type': 'Normal', 'Category': 'Physical', 'Power': 10, 'Accuracy': 90},
    163: {"Move": 'Slash', 'Type': 'Normal', 'Category': 'Physical', 'Power': 20, 'PP': 70, 'Accuracy': 100},
    164: {"Move": 'Substitute', 'Type': 'Normal', 'Category': 'Status', 'Power': 10},
    165: {"Move": 'Struggle', 'Type': 'Normal', 'Category': 'Physical', 'Power': 1, 'PP': 50}
}

poke_and_type_dict = {
    1: {'name': 'Rhydon', 'type1': 'Ground', 'type2': 'Rock'}, 
    2: {'name': 'Kangaskhan', 'type1': 'Normal', 'type2': ''}, 
    3: {'name': 'Nidoran♂', 'type1': 'Poison', 'type2': ''}, 
    4: {'name': 'Clefairy', 'type1': 'Normal', 'type2': ''}, 
    5: {'name': 'Spearow', 'type1': 'Normal', 'type2': 'Flying'}, 
    6: {'name': 'Voltorb', 'type1': 'Electric', 'type2': ''}, 
    7: {'name': 'Nidoking', 'type1': 'Poison', 'type2': 'Ground'}, 
    8: {'name': 'Slowbro', 'type1': 'Water', 'type2': 'Psychic'}, 
    9: {'name': 'Ivysaur', 'type1': 'Grass', 'type2': 'Poison'}, 
    10: {'name': 'Exeggutor', 'type1': 'Grass', 'type2': 'Psychic'}, 
    11: {'name': 'Lickitung', 'type1': 'Normal', 'type2': ''}, 
    12: {'name': 'Exeggcute', 'type1': 'Grass', 'type2': 'Psychic'}, 
    13: {'name': 'Grimer', 'type1': 'Poison', 'type2': ''}, 
    14: {'name': 'Gengar', 'type1': 'Ghost', 'type2': 'Poison'}, 
    15: {'name': 'Nidoran♀', 'type1': 'Poison', 'type2': ''}, 
    16: {'name': 'Nidoqueen', 'type1': 'Poison', 'type2': 'Ground'}, 
    17: {'name': 'Cubone', 'type1': 'Ground', 'type2': ''}, 
    18: {'name': 'Rhyhorn', 'type1': 'Ground', 'type2': 'Rock'}, 
    19: {'name': 'Lapras', 'type1': 'Water', 'type2': 'Ice'}, 
    20: {'name': 'Arcanine', 'type1': 'Fire', 'type2': ''}, 
    21: {'name': 'Mew', 'type1': 'Psychic', 'type2': ''}, 
    22: {'name': 'Gyarados', 'type1': 'Water', 'type2': 'Flying'}, 
    23: {'name': 'Shellder', 'type1': 'Water', 'type2': ''}, 
    24: {'name': 'Tentacool', 'type1': 'Water', 'type2': 'Poison'}, 
    25: {'name': 'Gastly', 'type1': 'Ghost', 'type2': 'Poison'}, 
    26: {'name': 'Scyther', 'type1': 'Bug', 'type2': 'Flying'}, 
    27: {'name': 'Staryu', 'type1': 'Water', 'type2': ''}, 
    28: {'name': 'Blastoise', 'type1': 'Water', 'type2': ''}, 
    29: {'name': 'Pinsir', 'type1': 'Bug', 'type2': ''}, 
    30: {'name': 'Tangela', 'type1': 'Grass', 'type2': ''}, 
    31: {'name': 'MissingNo. (Scizor)', 'type1': 'Bird', 'type2': 'Normal'}, 
    32: {'name': 'MissingNo. (Shuckle)', 'type1': 'Bird', 'type2': 'Normal'}, 
    33: {'name': 'Growlithe', 'type1': 'Fire', 'type2': ''}, 
    34: {'name': 'Onix', 'type1': 'Rock', 'type2': 'Ground'}, 
    35: {'name': 'Fearow', 'type1': 'Normal', 'type2': 'Flying'}, 
    36: {'name': 'Pidgey', 'type1': 'Normal', 'type2': 'Flying'}, 
    37: {'name': 'Slowpoke', 'type1': 'Water', 'type2': 'Psychic'}, 
    38: {'name': 'Kadabra', 'type1': 'Psychic', 'type2': ''}, 
    39: {'name': 'Graveler', 'type1': 'Rock', 'type2': 'Ground'}, 
    40: {'name': 'Chansey', 'type1': 'Normal', 'type2': ''}, 
    41: {'name': 'Machoke', 'type1': 'Fighting', 'type2': ''}, 
    42: {'name': 'Mr. Mime', 'type1': 'Psychic', 'type2': ''}, 
    43: {'name': 'Hitmonlee', 'type1': 'Fighting', 'type2': ''}, 
    44: {'name': 'Hitmonchan', 'type1': 'Fighting', 'type2': ''}, 
    45: {'name': 'Arbok', 'type1': 'Poison', 'type2': ''}, 
    46: {'name': 'Parasect', 'type1': 'Bug', 'type2': 'Grass'}, 
    47: {'name': 'Psyduck', 'type1': 'Water', 'type2': ''}, 
    48: {'name': 'Drowzee', 'type1': 'Psychic', 'type2': ''}, 
    49: {'name': 'Golem', 'type1': 'Rock', 'type2': 'Ground'}, 
    50: {'name': 'MissingNo. (Heracross)', 'type1': 'Bird', 'type2': 'Normal'}, 
    51: {'name': 'Magmar', 'type1': 'Fire', 'type2': ''}, 
    52: {'name': 'MissingNo. (Ho-Oh)', 'type1': 'Bird', 'type2': 'Normal'}, 
    53: {'name': 'Electabuzz', 'type1': 'Electric', 'type2': ''}, 
    54: {'name': 'Magneton', 'type1': 'Electric', 'type2': ''}, 
    55: {'name': 'Koffing', 'type1': 'Poison', 'type2': ''}, 
    56: {'name': 'MissingNo. (Sneasel)', 'type1': 'Bird', 'type2': 'Normal'}, 
    57: {'name': 'Mankey', 'type1': 'Fighting', 'type2': ''}, 
    58: {'name': 'Seel', 'type1': 'Water', 'type2': ''}, 
    59: {'name': 'Diglett', 'type1': 'Ground', 'type2': ''}, 
    60: {'name': 'Tauros', 'type1': 'Normal', 'type2': ''}, 
    61: {'name': 'MissingNo. (Teddiursa)', 'type1': 'Bird', 'type2': 'Normal'}, 
    62: {'name': 'MissingNo. (Ursaring)', 'type1': 'Bird', 'type2': 'Normal'}, 
    63: {'name': 'MissingNo. (Slugma)', 'type1': 'Bird', 'type2': 'Normal'}, 
    64: {'name': "Farfetch'd", 'type1': 'Normal', 'type2': 'Flying'}, 
    65: {'name': 'Venonat', 'type1': 'Bug', 'type2': 'Poison'}, 
    66: {'name': 'Dragonite', 'type1': 'Dragon', 'type2': 'Flying'}, 
    67: {'name': 'MissingNo. (Magcargo)', 'type1': 'Bird', 'type2': 'Normal'}, 
    68: {'name': 'MissingNo. (Swinub)', 'type1': 'Bird', 'type2': 'Normal'}, 
    69: {'name': 'MissingNo. (Piloswine)', 'type1': 'Bird', 'type2': 'Normal'}, 
    70: {'name': 'Doduo', 'type1': 'Normal', 'type2': 'Flying'}, 
    71: {'name': 'Poliwag', 'type1': 'Water', 'type2': ''}, 
    72: {'name': 'Jynx', 'type1': 'Ice', 'type2': 'Psychic'}, 
    73: {'name': 'Moltres', 'type1': 'Fire', 'type2': 'Flying'}, 
    74: {'name': 'Articuno', 'type1': 'Ice', 'type2': 'Flying'}, 
    75: {'name': 'Zapdos', 'type1': 'Electric', 'type2': 'Flying'}, 
    76: {'name': 'Ditto', 'type1': 'Normal', 'type2': ''}, 
    77: {'name': 'Meowth', 'type1': 'Normal', 'type2': ''}, 
    78: {'name': 'Krabby', 'type1': 'Water', 'type2': ''}, 
    79: {'name': 'MissingNo. (Corsola)', 'type1': 'Bird', 'type2': 'Normal'}, 
    80: {'name': 'MissingNo. (Remoraid)', 'type1': 'Bird', 'type2': 'Normal'}, 
    81: {'name': 'MissingNo. (Octillery)', 'type1': 'Bird', 'type2': 'Normal'}, 
    82: {'name': 'Vulpix', 'type1': 'Fire', 'type2': ''}, 
    83: {'name': 'Ninetales', 'type1': 'Fire', 'type2': ''}, 
    84: {'name': 'Pikachu', 'type1': 'Electric', 'type2': ''}, 
    85: {'name': 'Raichu', 'type1': 'Electric', 'type2': ''}, 
    86: {'name': 'MissingNo. (Delibird)', 'type1': 'Bird', 'type2': 'Normal'}, 
    87: {'name': 'MissingNo. (Mantine)', 'type1': 'Bird', 'type2': 'Normal'}, 
    88: {'name': 'Dratini', 'type1': 'Dragon', 'type2': ''}, 
    89: {'name': 'Dragonair', 'type1': 'Dragon', 'type2': ''}, 
    90: {'name': 'Kabuto', 'type1': 'Rock', 'type2': 'Water'}, 
    91: {'name': 'Kabutops', 'type1': 'Rock', 'type2': 'Water'}, 
    92: {'name': 'Horsea', 'type1': 'Water', 'type2': ''}, 
    93: {'name': 'Seadra', 'type1': 'Water', 'type2': ''}, 
    94: {'name': 'MissingNo. (Skarmory)', 'type1': 'Bird', 'type2': 'Normal'}, 
    95: {'name': 'MissingNo. (Houndour)', 'type1': 'Bird', 'type2': 'Normal'}, 
    96: {'name': 'Sandshrew', 'type1': 'Ground', 'type2': ''}, 
    97: {'name': 'Sandslash', 'type1': 'Ground', 'type2': ''}, 
    98: {'name': 'Omanyte', 'type1': 'Rock', 'type2': 'Water'}, 
    99: {'name': 'Omastar', 'type1': 'Rock', 'type2': 'Water'}, 
    100: {'name': 'Jigglypuff', 'type1': 'Normal', 'type2': ''}, 
    101: {'name': 'Wigglytuff', 'type1': 'Normal', 'type2': ''}, 
    102: {'name': 'Eevee', 'type1': 'Normal', 'type2': ''}, 
    103: {'name': 'Flareon', 'type1': 'Fire', 'type2': ''}, 
    104: {'name': 'Jolteon', 'type1': 'Electric', 'type2': ''}, 
    105: {'name': 'Vaporeon', 'type1': 'Water', 'type2': ''}, 
    106: {'name': 'Machop', 'type1': 'Fighting', 'type2': ''}, 
    107: {'name': 'Zubat', 'type1': 'Poison', 'type2': 'Flying'}, 
    108: {'name': 'Ekans', 'type1': 'Poison', 'type2': ''}, 
    109: {'name': 'Paras', 'type1': 'Bug', 'type2': 'Grass'}, 
    110: {'name': 'Poliwhirl', 'type1': 'Water', 'type2': ''}, 111: {'name': 'Poliwrath', 'type1': 'Water', 'type2': 'Fighting'}, 112: {'name': 'Weedle', 'type1': 'Bug', 'type2': 'Poison'}, 113: {'name': 'Kakuna', 'type1': 'Bug', 'type2': 'Poison'}, 114: {'name': 'Beedrill', 'type1': 'Bug', 'type2': 'Poison'}, 115: {'name': 'MissingNo. (Houndoom)', 'type1': 'Bird', 'type2': 'Normal'}, 116: {'name': 'Dodrio', 'type1': 'Normal', 'type2': 'Flying'}, 117: {'name': 'Primeape', 'type1': 'Fighting', 'type2': ''}, 118: {'name': 'Dugtrio', 'type1': 'Ground', 'type2': ''}, 119: {'name': 'Venomoth', 'type1': 'Bug', 'type2': 'Poison'}, 120: {'name': 'Dewgong', 'type1': 'Water', 'type2': 'Ice'}, 121: {'name': 'MissingNo. (Kingdra)', 'type1': 'Bird', 'type2': 'Normal'}, 122: {'name': 'MissingNo. (Phanpy)', 'type1': 'Bird', 'type2': 'Normal'}, 123: {'name': 'Caterpie', 'type1': 'Bug', 'type2': ''}, 124: {'name': 'Metapod', 'type1': 'Bug', 'type2': ''}, 125: {'name': 'Butterfree', 'type1': 'Bug', 'type2': 'Flying'}, 126: {'name': 'Machamp', 'type1': 'Fighting', 'type2': ''}, 127: {'name': 'MissingNo. (Donphan)', 'type1': 'Bird', 'type2': 'Normal'}, 128: {'name': 'Golduck', 'type1': 'Water', 'type2': ''}, 129: {'name': 'Hypno', 'type1': 'Psychic', 'type2': ''}, 130: {'name': 'Golbat', 'type1': 'Poison', 'type2': 'Flying'}, 131: {'name': 'Mewtwo', 'type1': 'Psychic', 'type2': ''}, 132: {'name': 'Snorlax', 'type1': 'Normal', 'type2': ''}, 133: {'name': 'Magikarp', 'type1': 'Water', 'type2': ''}, 134: {'name': 'MissingNo. (Porygon2)', 'type1': 'Bird', 'type2': 'Normal'}, 135: {'name': 'MissingNo. (Stantler)', 'type1': 'Bird', 'type2': 'Normal'}, 136: {'name': 'Muk', 'type1': 'Poison', 'type2': ''}, 137: {'name': 'MissingNo. (Smeargle)', 'type1': 'Bird', 'type2': 'Normal'}, 138: {'name': 'Kingler', 'type1': 'Water', 'type2': ''}, 139: {'name': 'Cloyster', 'type1': 'Water', 'type2': 'Ice'}, 140: {'name': 'MissingNo. (Tyrogue)', 'type1': 'Bird', 'type2': 'Normal'}, 141: {'name': 'Electrode', 'type1': 'Electric', 'type2': ''}, 142: {'name': 'Clefable', 'type1': 'Normal', 'type2': ''}, 143: {'name': 'Weezing', 'type1': 'Poison', 'type2': ''}, 144: {'name': 'Persian', 'type1': 'Normal', 'type2': ''}, 145: {'name': 'Marowak', 'type1': 'Ground', 'type2': ''}, 146: {'name': 'MissingNo. (Hitmontop)', 'type1': 'Bird', 'type2': 'Normal'}, 147: {'name': 'Haunter', 'type1': 'Ghost', 'type2': 'Poison'}, 148: {'name': 'Abra', 'type1': 'Psychic', 'type2': ''}, 149: {'name': 'Alakazam', 'type1': 'Psychic', 'type2': ''}, 150: {'name': 'Pidgeotto', 'type1': 'Normal', 'type2': 'Flying'}, 
    151: {'name': 'Pidgeot', 'type1': 'Normal', 'type2': 'Flying'}, 152: {'name': 'Starmie', 'type1': 'Water', 'type2': 'Psychic'}, 153: {'name': 'Bulbasaur', 'type1': 'Grass', 'type2': 'Poison'}, 154: {'name': 'Venusaur', 'type1': 'Grass', 'type2': 'Poison'}, 155: {'name': 'Tentacruel', 'type1': 'Water', 'type2': 'Poison'}, 156: {'name': 'MissingNo. (Smoochum)', 'type1': 'Bird', 'type2': 'Normal'}, 157: {'name': 'Goldeen', 'type1': 'Water', 'type2': ''}, 158: {'name': 'Seaking', 'type1': 'Water', 'type2': ''}, 159: {'name': 'MissingNo. (Elekid)', 'type1': 'Bird', 'type2': 'Normal'}, 160: {'name': 'MissingNo. (Magby)', 'type1': 'Bird', 'type2': 'Normal'}, 161: {'name': 'MissingNo. (Miltank)', 'type1': 'Bird', 'type2': 'Normal'}, 162: {'name': 'MissingNo. (Blissey)', 'type1': 'Bird', 'type2': 'Normal'}, 163: {'name': 'Ponyta', 'type1': 'Fire', 'type2': ''}, 164: {'name': 'Rapidash', 'type1': 'Fire', 'type2': ''}, 165: {'name': 'Rattata', 'type1': 'Normal', 'type2': ''}, 166: {'name': 'Raticate', 'type1': 'Normal', 'type2': ''}, 167: {'name': 'Nidorino', 'type1': 'Poison', 'type2': ''}, 168: {'name': 'Nidorina', 'type1': 'Poison', 'type2': ''}, 169: {'name': 'Geodude', 'type1': 'Rock', 'type2': 'Ground'}, 170: {'name': 'Porygon', 'type1': 'Normal', 'type2': ''}, 171: {'name': 'Aerodactyl', 'type1': 'Rock', 'type2': 'Flying'}, 172: {'name': 'MissingNo. (Raikou)', 'type1': 'Bird', 'type2': 'Normal'}, 173: {'name': 'Magnemite', 'type1': 'Electric', 'type2': ''}, 174: {'name': 'MissingNo. (Entei)', 'type1': 'Bird', 'type2': 'Normal'}, 175: {'name': 'MissingNo. (Suicune)', 'type1': 'Bird', 'type2': 'Normal'}, 176: {'name': 'Charmander', 'type1': 'Fire', 'type2': ''}, 177: {'name': 'Squirtle', 'type1': 'Water', 'type2': ''}, 178: {'name': 'Charmeleon', 'type1': 'Fire', 'type2': ''}, 179: {'name': 'Wartortle', 'type1': 'Water', 'type2': ''}, 180: {'name': 'Charizard', 'type1': 'Fire', 'type2': 'Flying'}, 181: {'name': 'MissingNo. (Larvitar)', 'type1': 'Bird', 'type2': 'Normal'}, 182: {'name': 'MissingNo. Kabutops Fossil (Pupitar)', 'type1': 'Bird', 'type2': 'Normal'}, 183: {'name': 'MissingNo. Aerodactyl Fossil (Tyranitar)', 'type1': 'Bird', 'type2': 'Normal'}, 184: {'name': 'MissingNo. Ghost (Lugia)', 'type1': 'Bird', 'type2': 'Normal'}, 185: {'name': 'Oddish', 'type1': 'Grass', 'type2': 'Poison'}, 186: {'name': 'Gloom', 'type1': 'Grass', 'type2': 'Poison'}, 187: {'name': 'Vileplume', 'type1': 'Grass', 'type2': 'Poison'}, 188: {'name': 'Bellsprout', 'type1': 'Grass', 'type2': 'Poison'}, 189: {'name': 'Weepinbell', 'type1': 'Grass', 'type2': 'Poison'}, 
    190: {'name': 'Victreebel', 'type1': 'Grass', 'type2': 'Poison'}}

map_dict = {
    0: 'Pallet Town',
    1: 'Viridian City',
    2: 'Pewter City',
    3: 'Cerulean City', 
    4: 'Lavender Town', 
    5: 'Vermilion City', 
    6: 'Celadon City', 
    7: 'Fuchsia City', 
    8: 'Cinnabar Island', 
    9: 'Pokémon League', 
    10: 'Saffron City', 
    11: 'Unused Fly location', 
    12: 'Route 1', 
    13: 'Route 2', 
    14: 'Route 3', 
    15: 'Route 4', 
    16: 'Route 5', 
    17: 'Route 6', 
    18: 'Route 7', 
    19: 'Route 8', 
    20: 'Route 9', 
    21: 'Route 10', 
    22: 'Route 11', 
    23: 'Route 12', 
    24: 'Route 13', 
    25: 'Route 14', 
    26: 'Route 15', 
    27: 'Route 16', 
    28: 'Route 17', 
    29: 'Route 18', 
    30: 'Sea Route 19', 
    31: 'Sea Route 20', 
    32: 'Sea Route 21', 
    33: 'Route 22', 
    34: 'Route 23', 
    35: 'Route 24', 
    36: 'Route 25', 
    37: 'Reds house (first floor)', 
    38: 'Reds house (second floor)', 
    39: 'Blues house', 
    40: 'Professor Oaks Lab', 
    41: 'Pokémon Center (Viridian City)', 
    42: 'Poké Mart (Viridian City)', 
    43: 'School (Viridian City)', 
    44: 'House 1 (Viridian City)', 
    45: 'Gym (Viridian City)', 
    46: 'Digletts Cave (Route 2 entrance)', 
    47: 'Gate (Viridian City/Pewter City) (Route 2)', 
    48: 'Oaks Aide House 1 (Route 2)', 
    49: 'Gate (Route 2)', 
    50: 'Gate (Route 2/Viridian Forest) (Route 2)', 
    51: 'Viridian Forest', 
    52: 'Pewter Museum (floor 1)', 
    53: 'Pewter Museum (floor 2)', 
    54: 'Gym (Pewter City)', 
    55: 'House with disobedient Nidoran♂ (Pewter City)', 
    56: 'Poké Mart (Pewter City)', 
    57: 'House with two Trainers (Pewter City)', 
    58: 'Pokémon Center (Pewter City)', 
    59: 'Mt. Moon (Route 3 entrance)', 
    60: 'Mt. Moon', 61: 'Mt. Moon', 
    62: 'Invaded house (Cerulean City)', 
    63: 'Poliwhirl for Jynx trade house', 
    64: 'Pokémon Center (Cerulean City)', 
    65: 'Gym (Cerulean City)', 
    66: 'Bike Shop (Cerulean City)', 
    67: 'Poké Mart (Cerulean City)', 
    68: 'Pokémon Center (Route 4)', 
    69: 'Invaded house - alternative music (Cerulean City)', 
    70: 'Saffron City Gate (Route 5)', 
    71: 'Entrance to Underground Path (Route 5)', 
    72: 'Daycare Center (Route 5)', 
    73: 'Saffron City Gate (Route 6)', 
    74: 'Entrance to Underground Path (Route 6)', 
    75: 'Entrance to Underground Path (alternative music) (Route 6)', 
    76: 'Saffron City Gate (Route 7)', 
    77: 'Entrance to Underground Path (Route 7)', 
    78: 'Entrance to Underground Path (unused) (Route 7)', 
    79: 'Saffron City Gate (Route 8)', 
    80: 'Entrance to Underground Path (Route 8)', 
    81: 'Pokémon Center (Rock Tunnel)', 
    82: 'Rock Tunnel', 
    83: 'Power Plant', 
    84: 'Gate 1F (Route 11-Route 12)', 
    85: 'Digletts Cave (Vermilion City entrance)', 
    86: 'Gate 2F (Route 11-Route 12)', 
    87: 'Gate (Route 12-Route 13)', 
    88: 'Sea Cottage', 
    89: 'Pokémon Center (Vermilion City)', 
    90: 'Pokémon Fan Club (Vermilion City)', 
    91: 'Poké Mart (Vermilion City)', 
    92: 'Gym (Vermilion City)', 
    93: 'House with Pidgey (Vermilion City)', 
    94: 'Vermilion Harbor (Vermilion City)', 
    95: 'S.S. Anne 1F', 
    96: 'S.S. Anne 2F', 
    97: 'S.S. Anne 3F', 
    98: 'S.S. Anne B1F', 
    99: 'S.S. Anne (Deck)', 
    100: 'S.S. Anne (Kitchen)', 
    101: 'S.S. Anne (Captains room)', 
    102: 'S.S. Anne 1F (Gentlemans room)', 
    103: 'S.S. Anne 2F (Gentlemans room)', 
    104: 'S.S. Anne B1F (Sailor/Fishermans room)', 
    105: 'Unused (Victory Road)', 
    106: 'Unused (Victory Road)', 
    107: 'Unused (Victory Road)', 
    108: 'Victory Road (Route 23 entrance)', 
    109: 'Unused (Pokémon League)', 
    110: 'Unused (Pokémon League)', 
    111: 'Unused (Pokémon League)', 
    112: 'Unused (Pokémon League)', 
    113: 'Lances Elite Four room', 
    114: 'Unused (Pokémon League)', 
    115: 'Unused (Pokémon League)', 
    116: 'Unused (Pokémon League)', 
    117: 'Unused (Pokémon League)', 
    118: 'Hall of Fame', 
    119: 'Underground Path (Route 5-Route 6)', 
    120: 'Blue (Champion)s room', 
    121: 'Underground Path (Route 7-Route 8)', 
    122: 'Celadon Department Store 1F', 
    123: 'Celadon Department Store 2F', 
    124: 'Celadon Department Store 3F', 
    125: 'Celadon Department Store 4F', 
    126: 'Celadon Department Store Rooftop Square', 
    127: 'Celadon Department Store Lift', 
    128: 'Celadon Mansion 1F', 
    129: 'Celadon Mansion 2F', 
    130: 'Celadon Mansion 3F', 
    131: 'Celadon Mansion 4F', 
    132: 'Celadon Mansion 4F (Eevee building)', 
    133: 'Pokémon Center (Celadon City)', 
    134: 'Gym (Celadon City)', 
    135: 'Rocket Game Corner (Celadon City)', 
    136: 'Celadon Department Store 5F', 
    137: 'Prize corner (Celadon City)', 
    138: 'Restaurant (Celadon City)', 
    139: 'House with Team Rocket members (Celadon City)', 
    140: 'Hotel (Celadon City)', 
    141: 'Pokémon Center (Lavender Town)', 
    142: 'Pokémon Tower 1F', 
    143: 'Pokémon Tower 2F', 
    144: 'Pokémon Tower 3F', 
    145: 'Pokémon Tower 4F', 
    146: 'Pokémon Tower 5F', 
    147: 'Pokémon Tower 6F', 
    148: 'Pokémon Tower 7F', 
    149: 'Mr. Fujis house (Lavender Town)', 
    150: 'Poké Mart (Lavender Town)', 
    151: 'House with NPC discussing Cubones mother', 
    152: 'Poké Mart (Fuchsia City)', 
    153: 'House with NPCs discussing Bill (Fuchsia City)', 
    154: 'Pokémon Center (Fuchsia City)', 
    155: 'Wardens house (Fuchsia City)', 
    156: 'Safari Zone gate (Fuchsia City)', 
    157: 'Gym (Fuchsia City)', 
    158: 'House with NPCs discussing Baoba (Fuchsia City)', 
    159: 'Seafoam Islands', 
    160: 'Seafoam Islands', 
    161: 'Seafoam Islands', 
    162: 'Seafoam Islands', 
    163: 'Vermilion City Fishing Brother', 
    164: 'Fuchsia City Fishing Brother', 
    165: 'Pokémon Mansion (1F)', 
    166: 'Gym (Cinnabar Island)', 
    167: 'Pokémon Lab (Cinnabar Island)', 
    168: 'Pokémon Lab - Trade room (Cinnabar Island)', 
    169: 'Pokémon Lab - Room with scientists (Cinnabar Island)', 
    170: 'Pokémon Lab - Fossil resurrection room (Cinnabar Island)', 
    171: 'Pokémon Center (Cinnabar Island)', 
    172: 'Poké Mart (Cinnabar Island)', 
    173: 'Poké Mart - alternative music (Cinnabar Island)', 
    174: 'Pokémon Center (Indigo Plateau)', 
    175: 'Copycats house 1F (Saffron City)', 
    176: 'Copycats house 2F (Saffron City)', 
    177: 'Fighting Dojo (Saffron City)', 
    178: 'Gym (Saffron City)', 
    179: 'House with Pidgey (Saffron City)', 
    180: 'Poké Mart (Saffron City)', 
    181: 'Silph Co. 1F', 
    182: 'Pokémon Center (Saffron City)', 
    183: 'Mr. Psychics house (Saffron City)', 
    184: 'Gate 1F (Route 15)', 
    185: 'Gate 2F (Route 15)', 
    186: 'Gate 1F (Cycling Road) (Route 16)', 
    187: 'Gate 2F (Cycling Road) (Route 16)', 
    188: 'Secret house (Cycling Road) (Route 16)', 
    189: 'Route 12 Fishing Brother', 
    190: 'Gate 1F (Route 18)', 
    191: 'Gate 2F (Route 18)', 
    192: 'Seafoam Islands', 
    193: 'Badges check gate (Route 22)', 
    194: 'Victory Road', 
    195: 'Gate 2F (Route 12)', 
    196: 'House with NPC and HM moves advice (Vermilion City)', 
    197: 'Digletts Cave', 
    198: 'Victory Road', 
    199: 'Team Rocket Hideout (B1F)', 
    200: 'Team Rocket Hideout (B2F)', 
    201: 'Team Rocket Hideout (B3F)', 
    202: 'Team Rocket Hideout (B4F)', 
    203: 'Team Rocket Hideout (Lift)', 
    204: 'Unused (Team Rocket Hideout)', 
    205: 'Unused (Team Rocket Hideout)', 
    206: 'Unused (Team Rocket Hideout)', 
    207: 'Silph Co. (2F)', 
    208: 'Silph Co. (3F)', 
    209: 'Silph Co. (4F)', 
    210: 'Silph Co. (5F)', 
    211: 'Silph Co. (6F)', 
    212: 'Silph Co. (7F)', 
    213: 'Silph Co. (8F)', 
    214: 'Pokémon Mansion (2F)', 
    215: 'Pokémon Mansion (3F)', 
    216: 'Pokémon Mansion (B1F)', 
    217: 'Safari Zone (Area 1)', 
    218: 'Safari Zone (Area 2)', 
    219: 'Safari Zone (Area 3)', 
    220: 'Safari Zone (Entrance)', 
    221: 'Safari Zone (Rest house 1)', 
    222: 'Safari Zone (Prize house)', 
    223: 'Safari Zone (Rest house 2)', 
    224: 'Safari Zone (Rest house 3)', 
    225: 'Safari Zone (Rest house 4)', 
    226: 'Cerulean Cave', 
    227: 'Cerulean Cave 1F', 
    228: 'Cerulean Cave B1F', 
    229: 'Name Raters house (Lavender Town)', 
    230: 'Cerulean City (Gym Badge man)', 
    231: 'Unused (Rock Tunnel)', 
    232: 'Rock Tunnel', 
    233: 'Silph Co. 9F', 
    234: 'Silph Co. 10F', 
    235: 'Silph Co. 11F', 
    236: 'Silph Co. Lift', 
    237: '(Invalid)', 
    238: '(Invalid)', 
    239: 'Cable Club Trade Center(*)', 
    240: 'Cable Club Colosseum(*)', 
    241: '(Invalid)', 
    242: '(Invalid)', 
    243: '(Invalid)', 
    244: '(Invalid)', 
    245: 'Loreleis room', 
    246: 'Brunos room', 
    247: 'Agathas room'
}

items_dict = {
    1: {'decimal': 1, 'hex': '0x01', 'Item': 'Master Ball'},
    2: {'decimal': 2, 'hex': '0x02', 'Item': 'Ultra Ball'},
    3: {'decimal': 3, 'hex': '0x03', 'Item': 'Great Ball'},
    4: {'decimal': 4, 'hex': '0x04', 'Item': 'Poké Ball'},
    5: {'decimal': 5, 'hex': '0x05', 'Item': 'Town Map'},
    6: {'decimal': 6, 'hex': '0x06', 'Item': 'Bicycle'},
    7: {'decimal': 7, 'hex': '0x07', 'Item': '?????'},
    8: {'decimal': 8, 'hex': '0x08', 'Item': 'Safari Ball'},
    9: {'decimal': 9, 'hex': '0x09', 'Item': 'Pokédex'},
    10: {'decimal': 10, 'hex': '0x0A', 'Item': 'Moon Stone'},
    11: {'decimal': 11, 'hex': '0x0B', 'Item': 'Antidote'},
    12: {'decimal': 12, 'hex': '0x0C', 'Item': 'Burn Heal'},
    13: {'decimal': 13, 'hex': '0x0D', 'Item': 'Ice Heal'},
    14: {'decimal': 14, 'hex': '0x0E', 'Item': 'Awakening'},
    15: {'decimal': 15, 'hex': '0x0F', 'Item': 'Parlyz Heal'},
    16: {'decimal': 16, 'hex': '0x10', 'Item': 'Full Restore'},
    17: {'decimal': 17, 'hex': '0x11', 'Item': 'Max Potion'},
    18: {'decimal': 18, 'hex': '0x12', 'Item': 'Hyper Potion'},
    19: {'decimal': 19, 'hex': '0x13', 'Item': 'Super Potion'},
    20: {'decimal': 20, 'hex': '0x14', 'Item': 'Potion'},
    21: {'decimal': 21, 'hex': '0x15', 'Item': 'BoulderBadge'},
    22: {'decimal': 22, 'hex': '0x16', 'Item': 'CascadeBadge'},
    23: {'decimal': 23, 'hex': '0x17', 'Item': 'ThunderBadge'},
    24: {'decimal': 24, 'hex': '0x18', 'Item': 'RainbowBadge'},
    25: {'decimal': 25, 'hex': '0x19', 'Item': 'SoulBadge'},
    26: {'decimal': 26, 'hex': '0x1A', 'Item': 'MarshBadge'},
    27: {'decimal': 27, 'hex': '0x1B', 'Item': 'VolcanoBadge'},
    28: {'decimal': 28, 'hex': '0x1C', 'Item': 'EarthBadge'},
    29: {'decimal': 29, 'hex': '0x1D', 'Item': 'Escape Rope'},
    30: {'decimal': 30, 'hex': '0x1E', 'Item': 'Repel'},
    31: {'decimal': 31, 'hex': '0x1F', 'Item': 'Old Amber'},
    32: {'decimal': 32, 'hex': '0x20', 'Item': 'Fire Stone'},
    33: {'decimal': 33, 'hex': '0x21', 'Item': 'Thunderstone'},
    34: {'decimal': 34, 'hex': '0x22', 'Item': 'Water Stone'},
    35: {'decimal': 35, 'hex': '0x23', 'Item': 'HP Up'},
    36: {'decimal': 36, 'hex': '0x24', 'Item': 'Protein'},
    37: {'decimal': 37, 'hex': '0x25', 'Item': 'Iron'},
    38: {'decimal': 38, 'hex': '0x26', 'Item': 'Carbos'},
    39: {'decimal': 39, 'hex': '0x27', 'Item': 'Calcium'},
    40: {'decimal': 40, 'hex': '0x28', 'Item': 'Rare Candy'},
    41: {'decimal': 41, 'hex': '0x29', 'Item': 'Dome Fossil'},
    42: {'decimal': 42, 'hex': '0x2A', 'Item': 'Helix Fossil'},
    43: {'decimal': 43, 'hex': '0x2B', 'Item': 'Secret Key'},
    44: {'decimal': 44, 'hex': '0x2C', 'Item': '?????'},
    45: {'decimal': 45, 'hex': '0x2D', 'Item': 'Bike Voucher'},
    46: {'decimal': 46, 'hex': '0x2E', 'Item': 'X Accuracy'},
    47: {'decimal': 47, 'hex': '0x2F', 'Item': 'Leaf Stone'},
    48: {'decimal': 48, 'hex': '0x30', 'Item': 'Card Key'},
    49: {'decimal': 49, 'hex': '0x31', 'Item': 'Nugget'},
    50: {'decimal': 50, 'hex': '0x32', 'Item': 'PP Up*'},
    51: {'decimal': 51, 'hex': '0x33', 'Item': 'Poké Doll'},
    52: {'decimal': 52, 'hex': '0x34', 'Item': 'Full Heal'},
    53: {'decimal': 53, 'hex': '0x35', 'Item': 'Revive'},
    54: {'decimal': 54, 'hex': '0x36', 'Item': 'Max Revive'},
    55: {'decimal': 55, 'hex': '0x37', 'Item': 'Guard Spec.'},
    56: {'decimal': 56, 'hex': '0x38', 'Item': 'Super Repel'},
    57: {'decimal': 57, 'hex': '0x39', 'Item': 'Max Repel'},
    58: {'decimal': 58, 'hex': '0x3A', 'Item': 'Dire Hit'},
    59: {'decimal': 59, 'hex': '0x3B', 'Item': 'Coin'},
    60: {'decimal': 60, 'hex': '0x3C', 'Item': 'Fresh Water'},
    61: {'decimal': 61, 'hex': '0x3D', 'Item': 'Soda Pop'},
    62: {'decimal': 62, 'hex': '0x3E', 'Item': 'Lemonade'},
    63: {'decimal': 63, 'hex': '0x3F', 'Item': 'S.S. Ticket'},
    64: {'decimal': 64, 'hex': '0x40', 'Item': 'Gold Teeth'},
    65: {'decimal': 65, 'hex': '0x41', 'Item': 'X Attack'},
    66: {'decimal': 66, 'hex': '0x42', 'Item': 'X Defend'},
    67: {'decimal': 67, 'hex': '0x43', 'Item': 'X Speed'},
    68: {'decimal': 68, 'hex': '0x44', 'Item': 'X Special'},
    69: {'decimal': 69, 'hex': '0x45', 'Item': 'Coin Case'},
    70: {'decimal': 70, 'hex': '0x46', 'Item': "Oak's Parcel"},
    71: {'decimal': 71, 'hex': '0x47', 'Item': 'Itemfinder'},
    72: {'decimal': 72, 'hex': '0x48', 'Item': 'Silph Scope'},
    73: {'decimal': 73, 'hex': '0x49', 'Item': 'Poké Flute'},
    74: {'decimal': 74, 'hex': '0x4A', 'Item': 'Lift Key'},
    75: {'decimal': 75, 'hex': '0x4B', 'Item': 'Exp. All'},
    76: {'decimal': 76, 'hex': '0x4C', 'Item': 'Old Rod'},
    77: {'decimal': 77, 'hex': '0x4D', 'Item': 'Good Rod'},
    78: {'decimal': 78, 'hex': '0x4E', 'Item': 'Super Rod'},
    79: {'decimal': 79, 'hex': '0x4F', 'Item': 'PP Up'},
    80: {'decimal': 80, 'hex': '0x50', 'Item': 'Ether'},
    81: {'decimal': 81, 'hex': '0x51', 'Item': 'Max Ether'},
    82: {'decimal': 82, 'hex': '0x52', 'Item': 'Elixer'},
    83: {'decimal': 83, 'hex': '0x53', 'Item': 'Max Elixer'},
    196: {'decimal': 196, 'hex': '0xC4', 'Item': 'HM01'},
    197: {'decimal': 197, 'hex': '0xC5', 'Item': 'HM02'},
    198: {'decimal': 198, 'hex': '0xC6', 'Item': 'HM03'},
    199: {'decimal': 199, 'hex': '0xC7', 'Item': 'HM04'},
    200: {'decimal': 200, 'hex': '0xC8', 'Item': 'HM05'},
    201: {'decimal': 201, 'hex': '0xC9', 'Item': 'TM01'},
    202: {'decimal': 202, 'hex': '0xCA', 'Item': 'TM02'},
    203: {'decimal': 203, 'hex': '0xCB', 'Item': 'TM03'},
    204: {'decimal': 204, 'hex': '0xCC', 'Item': 'TM04'},
    205: {'decimal': 205, 'hex': '0xCD', 'Item': 'TM05'},
    206: {'decimal': 206, 'hex': '0xCE', 'Item': 'TM06'},
    207: {'decimal': 207, 'hex': '0xCF', 'Item': 'TM07'},
    208: {'decimal': 208, 'hex': '0xD0', 'Item': 'TM08'},
    209: {'decimal': 209, 'hex': '0xD1', 'Item': 'TM09'},
    210: {'decimal': 210, 'hex': '0xD2', 'Item': 'TM10'},
    211: {'decimal': 211, 'hex': '0xD3', 'Item': 'TM11'},
    212: {'decimal': 212, 'hex': '0xD4', 'Item': 'TM12'},
    213: {'decimal': 213, 'hex': '0xD5', 'Item': 'TM13'},
    214: {'decimal': 214, 'hex': '0xD6', 'Item': 'TM14'},
    215: {'decimal': 215, 'hex': '0xD7', 'Item': 'TM15'},
    216: {'decimal': 216, 'hex': '0xD8', 'Item': 'TM16'},
    217: {'decimal': 217, 'hex': '0xD9', 'Item': 'TM17'},
    218: {'decimal': 218, 'hex': '0xDA', 'Item': 'TM18'},
    219: {'decimal': 219, 'hex': '0xDB', 'Item': 'TM19'},
    220: {'decimal': 220, 'hex': '0xDC', 'Item': 'TM20'},
    221: {'decimal': 221, 'hex': '0xDD', 'Item': 'TM21'},
    222: {'decimal': 222, 'hex': '0xDE', 'Item': 'TM22'},
    223: {'decimal': 223, 'hex': '0xDF', 'Item': 'TM23'},
    224: {'decimal': 224, 'hex': '0xE0', 'Item': 'TM24'},
    225: {'decimal': 225, 'hex': '0xE1', 'Item': 'TM25'},
    226: {'decimal': 226, 'hex': '0xE2', 'Item': 'TM26'},
    227: {'decimal': 227, 'hex': '0xE3', 'Item': 'TM27'},
    228: {'decimal': 228, 'hex': '0xE4', 'Item': 'TM28'},
    229: {'decimal': 229, 'hex': '0xE5', 'Item': 'TM29'},
    230: {'decimal': 230, 'hex': '0xE6', 'Item': 'TM30'},
    231: {'decimal': 231, 'hex': '0xE7', 'Item': 'TM31'},
    232: {'decimal': 232, 'hex': '0xE8', 'Item': 'TM32'},
    233: {'decimal': 233, 'hex': '0xE9', 'Item': 'TM33'},
    234: {'decimal': 234, 'hex': '0xEA', 'Item': 'TM34'},
    235: {'decimal': 235, 'hex': '0xEB', 'Item': 'TM35'},
    236: {'decimal': 236, 'hex': '0xEC', 'Item': 'TM36'},
    237: {'decimal': 237, 'hex': '0xED', 'Item': 'TM37'},
    238: {'decimal': 238, 'hex': '0xEE', 'Item': 'TM38'},
    239: {'decimal': 239, 'hex': '0xEF', 'Item': 'TM39'},
    240: {'decimal': 240, 'hex': '0xF0', 'Item': 'TM40'},
    241: {'decimal': 241, 'hex': '0xF1', 'Item': 'TM41'},
    242: {'decimal': 242, 'hex': '0xF2', 'Item': 'TM42'},
    243: {'decimal': 243, 'hex': '0xF3', 'Item': 'TM43'},
    244: {'decimal': 244, 'hex': '0xF4', 'Item': 'TM44'},
    245: {'decimal': 245, 'hex': '0xF5', 'Item': 'TM45'},
    246: {'decimal': 246, 'hex': '0xF6', 'Item': 'TM46'},
    247: {'decimal': 247, 'hex': '0xF7', 'Item': 'TM47'},
    248: {'decimal': 248, 'hex': '0xF8', 'Item': 'TM48'},
    249: {'decimal': 249, 'hex': '0xF9', 'Item': 'TM49'},
    250: {'decimal': 250, 'hex': '0xFA', 'Item': 'TM50'},
    251: {'decimal': 251, 'hex': '0xFB', 'Item': 'TM51'},
    252: {'decimal': 252, 'hex': '0xFC', 'Item': 'TM52'},
    253: {'decimal': 253, 'hex': '0xFD', 'Item': 'TM53'},
    254: {'decimal': 254, 'hex': '0xFE', 'Item': 'TM54'},
    255: {'decimal': 255, 'hex': '0xFF', 'Item': 'TM55'},
}

poke_dict = {
    1: {'hex': '1', 'decimal': '1', 'name': 'Rhydon'},
    2: {'hex': '2', 'decimal': '2', 'name': 'Kangaskhan'},
    3: {'hex': '3', 'decimal': '3', 'name': 'Nidoran♂'},
    4: {'hex': '4', 'decimal': '4', 'name': 'Clefairy'},
    5: {'hex': '5', 'decimal': '5', 'name': 'Spearow'},
    6: {'hex': '6', 'decimal': '6', 'name': 'Voltorb', 'type': 'Electric'},
    7: {'hex': '7', 'decimal': '7', 'name': 'Nidoking'},
    8: {'hex': '8', 'decimal': '8', 'name': 'Slowbro'},
    9: {'hex': '9', 'decimal': '9', 'name': 'Ivysaur'},
    10: {'hex': 'A', 'decimal': '10', 'name': 'Exeggutor'},
    11: {'hex': 'B', 'decimal': '11', 'name': 'Lickitung'},
    12: {'hex': 'C', 'decimal': '12', 'name': 'Exeggcute'},
    13: {'hex': 'D', 'decimal': '13', 'name': 'Grimer'},
    14: {'hex': 'E', 'decimal': '14', 'name': 'Gengar', 'type': 'Ghost'},
    15: {'hex': 'F', 'decimal': '15', 'name': 'Nidoran♀'},
    16: {'hex': '10', 'decimal': '16', 'name': 'Nidoqueen'},
    17: {'hex': '11', 'decimal': '17', 'name': 'Cubone'},
    18: {'hex': '12', 'decimal': '18', 'name': 'Rhyhorn'},
    19: {'hex': '13', 'decimal': '19', 'name': 'Lapras', 'type': 'Ice'},
    20: {'hex': '14', 'decimal': '20', 'name': 'Arcanine'},
    21: {'hex': '15', 'decimal': '21', 'name': 'Mew'},
    22: {'hex': '16', 'decimal': '22', 'name': 'Gyarados'},
    23: {'hex': '17', 'decimal': '23', 'name': 'Shellder'},
    24: {'hex': '18', 'decimal': '24', 'name': 'Tentacool'},
    25: {'hex': '19', 'decimal': '25', 'name': 'Gastly', 'type': 'Ghost'},
    26: {'hex': '1A', 'decimal': '26', 'name': 'Scyther', 'type': 'Bug'},
    27: {'hex': '1B', 'decimal': '27', 'name': 'Staryu'},
    28: {'hex': '1C', 'decimal': '28', 'name': 'Blastoise'},
    29: {'hex': '1D', 'decimal': '29', 'name': 'Pinsir', 'type': 'Bug'},
    30: {'hex': '1E', 'decimal': '30', 'name': 'Tangela'},
    31: {'hex': '1F', 'decimal': '31', 'name': 'MissingNo. (Scizor)'},
    32: {'hex': '20', 'decimal': '32', 'name': 'MissingNo. (Shuckle)'},
    33: {'hex': '21', 'decimal': '33', 'name': 'Growlithe'},
    34: {'hex': '22', 'decimal': '34', 'name': 'Onix'},
    35: {'hex': '23', 'decimal': '35', 'name': 'Fearow'},
    36: {'hex': '24', 'decimal': '36', 'name': 'Pidgey'},
    37: {'hex': '25', 'decimal': '37', 'name': 'Slowpoke'},
    38: {'hex': '26', 'decimal': '38', 'name': 'Kadabra'},
    39: {'hex': '27', 'decimal': '39', 'name': 'Graveler'},
    40: {'hex': '28', 'decimal': '40', 'name': 'Chansey'},
    41: {'hex': '29', 'decimal': '41', 'name': 'Machoke'},
    42: {'hex': '2A', 'decimal': '42', 'name': 'Mr. Mime'},
    43: {'hex': '2B', 'decimal': '43', 'name': 'Hitmonlee'},
    44: {'hex': '2C', 'decimal': '44', 'name': 'Hitmonchan'},
    45: {'hex': '2D', 'decimal': '45', 'name': 'Arbok'},
    46: {'hex': '2E', 'decimal': '46', 'name': 'Parasect', 'type': 'Bug'},
    47: {'hex': '2F', 'decimal': '47', 'name': 'Psyduck'},
    48: {'hex': '30', 'decimal': '48', 'name': 'Drowzee'},
    49: {'hex': '31', 'decimal': '49', 'name': 'Golem'},
    50: {'hex': '32', 'decimal': '50', 'name': 'MissingNo. (Heracross)'},
    51: {'hex': '33', 'decimal': '51', 'name': 'Magmar'},
    52: {'hex': '34', 'decimal': '52', 'name': 'MissingNo. (Ho-Oh)'},
    53: {'hex': '35', 'decimal': '53', 'name': 'Electabuzz', 'type': 'Electric'},
    54: {'hex': '36', 'decimal': '54', 'name': 'Magneton', 'type': 'Electric'},
    55: {'hex': '37', 'decimal': '55', 'name': 'Koffing'},
    56: {'hex': '38', 'decimal': '56', 'name': 'MissingNo. (Sneasel)'},
    57: {'hex': '39', 'decimal': '57', 'name': 'Mankey'},
    58: {'hex': '3A', 'decimal': '58', 'name': 'Seel'},
    59: {'hex': '3B', 'decimal': '59', 'name': 'Diglett'},
    60: {'hex': '3C', 'decimal': '60', 'name': 'Tauros'},
    61: {'hex': '3D', 'decimal': '61', 'name': 'MissingNo. (Teddiursa)'},
    62: {'hex': '3E', 'decimal': '62', 'name': 'MissingNo. (Ursaring)'},
    63: {'hex': '3F', 'decimal': '63', 'name': 'MissingNo. (Slugma)'},
    64: {'hex': '40', 'decimal': '64', 'name': "Farfetch'd"},
    65: {'hex': '41', 'decimal': '65', 'name': 'Venonat', 'type': 'Bug'},
    66: {'hex': '42', 'decimal': '66', 'name': 'Dragonite', 'type': 'Dragon'},
    67: {'hex': '43', 'decimal': '67', 'name': 'MissingNo. (Magcargo)'},
    68: {'hex': '44', 'decimal': '68', 'name': 'MissingNo. (Swinub)'},
    69: {'hex': '45', 'decimal': '69', 'name': 'MissingNo. (Piloswine)'},
    70: {'hex': '46', 'decimal': '70', 'name': 'Doduo'},
    71: {'hex': '47', 'decimal': '71', 'name': 'Poliwag'},
    72: {'hex': '48', 'decimal': '72', 'name': 'Jynx', 'type': 'Ice'},
    73: {'hex': '49', 'decimal': '73', 'name': 'Moltres'},
    74: {'hex': '4A', 'decimal': '74', 'name': 'Articuno', 'type': 'Ice'},
    75: {'hex': '4B', 'decimal': '75', 'name': 'Zapdos', 'type': 'Electric'},
    76: {'hex': '4C', 'decimal': '76', 'name': 'Ditto'},
    77: {'hex': '4D', 'decimal': '77', 'name': 'Meowth'},
    78: {'hex': '4E', 'decimal': '78', 'name': 'Krabby'},
    79: {'hex': '4F', 'decimal': '79', 'name': 'MissingNo. (Corsola)'},
    80: {'hex': '50', 'decimal': '80', 'name': 'MissingNo. (Remoraid)'},
    81: {'hex': '51', 'decimal': '81', 'name': 'MissingNo. (Octillery)'},
    82: {'hex': '52', 'decimal': '82', 'name': 'Vulpix'},
    83: {'hex': '53', 'decimal': '83', 'name': 'Ninetales'},
    84: {'hex': '54', 'decimal': '84', 'name': 'Pikachu', 'type': 'Electric'},
    85: {'hex': '55', 'decimal': '85', 'name': 'Raichu', 'type': 'Electric'},
    86: {'hex': '56', 'decimal': '86', 'name': 'MissingNo. (Deli)'},
    87: {'hex': '57', 'decimal': '87', 'name': 'MissingNo. (Mantine)'},
    88: {'hex': '58', 'decimal': '88', 'name': 'Dratini', 'type': 'Dragon'},
    89: {'hex': '59', 'decimal': '89', 'name': 'Dragonair', 'type': 'Dragon'},
    90: {'hex': '5A', 'decimal': '90', 'name': 'Kabuto'},
    91: {'hex': '5B', 'decimal': '91', 'name': 'Kabutops'},
    92: {'hex': '5C', 'decimal': '92', 'name': 'Horsea'},
    93: {'hex': '5D', 'decimal': '93', 'name': 'Seadra'},
    94: {'hex': '5E', 'decimal': '94', 'name': 'MissingNo. (Skarmory)'},
    95: {'hex': '5F', 'decimal': '95', 'name': 'MissingNo. (Houndour)'},
    96: {'hex': '60', 'decimal': '96', 'name': 'Sandshrew'},
    97: {'hex': '61', 'decimal': '97', 'name': 'Sandslash'},
    98: {'hex': '62', 'decimal': '98', 'name': 'Omanyte'},
    99: {'hex': '63', 'decimal': '99', 'name': 'Omastar'},
    100: {'hex': '64', 'decimal': '100', 'name': 'Jigglypuff'},
    101: {'hex': '65', 'decimal': '101', 'name': 'Wigglytuff'},
    102: {'hex': '66', 'decimal': '102', 'name': 'Eevee'},
    103: {'hex': '67', 'decimal': '103', 'name': 'Flareon'},
    104: {'hex': '68', 'decimal': '104', 'name': 'Jolteon', 'type': 'Electric'},
    105: {'hex': '69', 'decimal': '105', 'name': 'Vaporeon'},
    106: {'hex': '6A', 'decimal': '106', 'name': 'Machop'},
    107: {'hex': '6B', 'decimal': '107', 'name': 'Zubat'},
    108: {'hex': '6C', 'decimal': '108', 'name': 'Ekans'},
    109: {'hex': '6D', 'decimal': '109', 'name': 'Paras', 'type': 'Bug'},
    110: {'hex': '6E', 'decimal': '110', 'name': 'Poliwhirl'},
    111: {'hex': '6F', 'decimal': '111', 'name': 'Poliwrath'},
    112: {'hex': '70', 'decimal': '112', 'name': 'Weedle', 'type': 'Bug'},
    113: {'hex': '71', 'decimal': '113', 'name': 'Kakuna', 'type': 'Bug'},
    114: {'hex': '72', 'decimal': '114', 'name': 'Beedrill', 'type': 'Bug'},
    115: {'hex': '73', 'decimal': '115', 'name': 'MissingNo. (Houndoom)'},
    116: {'hex': '74', 'decimal': '116', 'name': 'Dodrio'},
    117: {'hex': '75', 'decimal': '117', 'name': 'Primeape'},
    118: {'hex': '76', 'decimal': '118', 'name': 'Dugtrio'},
    119: {'hex': '77', 'decimal': '119', 'name': 'Venomoth', 'type': 'Bug'},
    120: {'hex': '78', 'decimal': '120', 'name': 'Dewgong', 'type': 'Ice'},
    121: {'hex': '79', 'decimal': '121', 'name': 'MissingNo. (Kingdra)'},
    122: {'hex': '7A', 'decimal': '122', 'name': 'MissingNo. (Phanpy)'},
    123: {'hex': '7B', 'decimal': '123', 'name': 'Caterpie', 'type': 'Bug'},
    124: {'hex': '7C', 'decimal': '124', 'name': 'Metapod', 'type': 'Bug'},
    125: {'hex': '7D', 'decimal': '125', 'name': 'Butterfree', 'type': 'Bug'},
    126: {'hex': '7E', 'decimal': '126', 'name': 'Machamp'},
    127: {'hex': '7F', 'decimal': '127', 'name': 'MissingNo. (Donphan)'},
    128: {'hex': '80', 'decimal': '128', 'name': 'Golduck'},
    129: {'hex': '81', 'decimal': '129', 'name': 'Hypno'},
    130: {'hex': '82', 'decimal': '130', 'name': 'Golbat'},
    131: {'hex': '83', 'decimal': '131', 'name': 'Mewtwo'},
    132: {'hex': '84', 'decimal': '132', 'name': 'Snorlax'},
    133: {'hex': '85', 'decimal': '133', 'name': 'Magikarp'},
    134: {'hex': '86', 'decimal': '134', 'name': 'MissingNo. (Porygon2)'},
    135: {'hex': '87', 'decimal': '135', 'name': 'MissingNo. (Stantler)'},
    136: {'hex': '88', 'decimal': '136', 'name': 'Muk'},
    137: {'hex': '89', 'decimal': '137', 'name': 'MissingNo. (Smeargle)'},
    138: {'hex': '8A', 'decimal': '138', 'name': 'Kingler'},
    139: {'hex': '8B', 'decimal': '139', 'name': 'Cloyster'},
    141: {'hex': '8D', 'decimal': '141', 'name': 'Electrode'},
    142: {'hex': '8E', 'decimal': '142', 'name': 'Clefable'},
    143: {'hex': '8F', 'decimal': '143', 'name': 'Weezing'},
    144: {'hex': '90', 'decimal': '144', 'name': 'Persian'},
    145: {'hex': '91', 'decimal': '145', 'name': 'Marowak'},
    147: {'hex': '93', 'decimal': '147', 'name': 'Haunter'},
    148: {'hex': '94', 'decimal': '148', 'name': 'Abra'},
    149: {'hex': '95', 'decimal': '149', 'name': 'Alakazam'},
    150: {'hex': '96', 'decimal': '150', 'name': 'Pidgeotto'},
    151: {'hex': '97', 'decimal': '151', 'name': 'Pidgeot'},
    152: {'hex': '98', 'decimal': '152', 'name': 'Starmie'},
    153: {'hex': '99', 'decimal': '153', 'name': 'Bulbasaur'},
    154: {'hex': '9A', 'decimal': '154', 'name': 'Venusaur'},
    155: {'hex': '9B', 'decimal': '155', 'name': 'Tentacruel'},
    157: {'hex': '9D', 'decimal': '157', 'name': 'Goldeen'},
    158: {'hex': '9E', 'decimal': '158', 'name': 'Seaking'},
    163: {'hex': 'A3', 'decimal': '163', 'name': 'Ponyta'},
    164: {'hex': 'A4', 'decimal': '164', 'name': 'Rapidash'},
    165: {'hex': 'A5', 'decimal': '165', 'name': 'Rattata'},
    166: {'hex': 'A6', 'decimal': '166', 'name': 'Raticate'},
    167: {'hex': 'A7', 'decimal': '167', 'name': 'Nidorino'},
    168: {'hex': 'A8', 'decimal': '168', 'name': 'Nidorina'},
    169: {'hex': 'A9', 'decimal': '169', 'name': 'Geodude'},
    170: {'hex': 'AA', 'decimal': '170', 'name': 'Porygon'},
    171: {'hex': 'AB', 'decimal': '171', 'name': 'Aerodactyl'},
    173: {'hex': 'AD', 'decimal': '173', 'name': 'Magnemite'},
    176: {'hex': 'B0', 'decimal': '176', 'name': 'Charmander'},
    177: {'hex': 'B1', 'decimal': '177', 'name': 'Squirtle'},
    178: {'hex': 'B2', 'decimal': '178', 'name': 'Charmeleon'},
    179: {'hex': 'B3', 'decimal': '179', 'name': 'Wartortle'},
    180: {'hex': 'B4', 'decimal': '180', 'name': 'Charizard'},
    185: {'hex': 'B9', 'decimal': '185', 'name': 'Oddish'},
    186: {'hex': 'BA', 'decimal': '186', 'name': 'Gloom'},
    187: {'hex': 'BB', 'decimal': '187', 'name': 'Vileplume'},
    188: {'hex': 'BC', 'decimal': '188', 'name': 'Bellsprout'},
    189: {'hex': 'BD', 'decimal': '189', 'name': 'Weepinbell'},
    190: {'hex': 'BE', 'decimal': '190', 'name': 'Victreebel'}
    }

type_dict = {
    0: 'Normal',
    1: 'Fighting',
    2: 'Flying',
    3: 'Poison',
    4: 'Ground',
    5: 'Rock',
    6: 'Bug',
    7: 'Ghost',
    8: 'fire',
    9: 'Water',
    10: 'Grass',
    11: 'Electric',
    12: 'Psychic',
    13: 'Ice',
    14: 'Dragon',}